/*
 * 윤이 영어 — 학습 콘텐츠
 * ------------------------------------------------------------
 * 아빠가 직접 고치는 파일이에요.
 *  - 주제마다 단어 50개(하루 5개씩 10일), 질문 20개(하루 2개씩 10일)
 *    목록 순서대로 1일차 → 10일차에 새로 나와요. 앞 일차 단어·질문은 매일 복습으로 섞여 나와요.
 *  - 단어: { en, ko, img, d } 한 줄 (img = 이모지, d = 단어 노래에서 읽어주는 한국어 설명)
 *  - alt: 아이 발음이 이렇게 인식돼도 정답으로 인정할 단어들 (선택)
 *  - photo: 'photos/dad.jpg' 처럼 넣으면 이모지 대신 사진 표시 (선택)
 *  - questions: 대화 질문. keywords 중 하나라도 들리면 정답
 *    {NAME} {AGE} {HYUN_REL} 은 아빠 화면 설정값으로 바뀜
 *  - 고친 뒤 sw.js 의 VERSION 숫자를 올려야 설치된 앱에 반영돼요.
 */
window.CONTENT = {
  topics: [
    {
      id: 'me', title: '나와 생활', en: 'Me & My Day', icon: '🙋', sticker: '🌟',
      words: [
        { en: 'hello', ko: '안녕', img: '👋', d: '만날 때 하는 인사야' },
        { en: 'name', ko: '이름', img: '📛', d: '나를 부르는 말이야' },
        { en: 'boy', ko: '남자아이', img: '👦', d: '남자 아이를 말해' },
        { en: 'girl', ko: '여자아이', img: '👧', d: '여자 아이를 말해' },
        { en: 'friend', ko: '친구', img: '🧑‍🤝‍🧑', d: '같이 노는 친구야' },
        { en: 'happy', ko: '행복한', img: '😊', d: '기분이 좋을 때 쓰는 말이야' },
        { en: 'yes', ko: '네', img: '⭕', d: '맞다고 할 때 말해' },
        { en: 'no', ko: '아니요', img: '❌', d: '아니라고 할 때 말해' },
        { en: 'me', ko: '나', img: '🙋', d: '바로 나 자신이야' },
        { en: 'you', ko: '너', img: '👉', d: '내 앞에 있는 너야' },
        { en: 'thank you', ko: '고마워', img: '🙏', d: '고마울 때 하는 말이야', alt: ['thanks', 'thank'] },
        { en: 'sorry', ko: '미안해', img: '😔', d: '미안할 때 하는 말이야' },
        { en: 'please', ko: '부탁해요', img: '🥺', d: '부탁할 때 붙이는 말이야', alt: ['plays', 'pleas'] },
        { en: 'okay', ko: '좋아', img: '👌', d: '괜찮다, 좋다는 말이야', alt: ['ok', 'o k'] },
        { en: 'good morning', ko: '좋은 아침', img: '🌅', d: '아침에 하는 인사야', alt: ['morning'] },
        { en: 'good night', ko: '잘 자', img: '🌙', d: '잘 때 하는 인사야', alt: ['night', 'goodnight'] },
        { en: 'school', ko: '학교', img: '🏫', d: '공부하고 친구를 만나는 곳이야' },
        { en: 'teacher', ko: '선생님', img: '🧑‍🏫', d: '학교에서 가르쳐 주시는 분이야' },
        { en: 'student', ko: '학생', img: '🧑‍🎓', d: '학교에서 배우는 사람이야' },
        { en: 'book', ko: '책', img: '📕', d: '글과 그림이 있어' },
        { en: 'pencil', ko: '연필', img: '✏️', d: '글씨를 쓰는 거야' },
        { en: 'crayon', ko: '크레파스', img: '🖍️', d: '알록달록 색칠해' },
        { en: 'scissors', ko: '가위', img: '✂️', d: '종이를 싹둑 잘라', alt: ['scissor'] },
        { en: 'ruler', ko: '자', img: '📏', d: '길이를 재거나 줄을 그어' },
        { en: 'notebook', ko: '공책', img: '📓', d: '글씨를 쓰는 책이야', alt: ['note book'] },
        { en: 'chair', ko: '의자', img: '🪑', d: '앉는 거야', alt: ['share', 'cheer'] },
        { en: 'clock', ko: '시계', img: '⏰', d: '몇 시인지 알려줘' },
        { en: 'bed', ko: '침대', img: '🛏️', d: '밤에 자는 곳이야', alt: ['bad', 'bread'] },
        { en: 'house', ko: '집', img: '🏠', d: '우리가 사는 곳이야' },
        { en: 'door', ko: '문', img: '🚪', d: '열고 닫고 드나들어' },
        { en: 'window', ko: '창문', img: '🪟', d: '밖이 보이는 유리야' },
        { en: 'toy', ko: '장난감', img: '🧸', d: '가지고 노는 거야', alt: ['toys'] },
        { en: 'ball', ko: '공', img: '⚽', d: '데굴데굴 굴러가', alt: ['bowl', 'bull'] },
        { en: 'doll', ko: '인형', img: '🪆', d: '안고 노는 인형이야', alt: ['dog', 'dull'] },
        { en: 'game', ko: '게임', img: '🎮', d: '재미있게 하는 놀이야' },
        { en: 'phone', ko: '전화기', img: '📱', d: '전화하고 사진도 찍어' },
        { en: 'TV', ko: '텔레비전', img: '📺', d: '만화를 볼 수 있어', alt: ['tv', 't v', 'tee vee', 'television'] },
        { en: 'shoes', ko: '신발', img: '👟', d: '발에 신어', alt: ['shoe'] },
        { en: 'hat', ko: '모자', img: '🧢', d: '머리에 써', alt: ['hot', 'hut'] },
        { en: 'shirt', ko: '셔츠', img: '👕', d: '몸에 입는 옷이야' },
        { en: 'pants', ko: '바지', img: '👖', d: '다리에 입는 옷이야', alt: ['pant'] },
        { en: 'socks', ko: '양말', img: '🧦', d: '신발 신기 전에 신어', alt: ['sock', 'sucks'] },
        { en: 'glasses', ko: '안경', img: '👓', d: '눈에 쓰면 잘 보여', alt: ['glass'] },
        { en: 'umbrella', ko: '우산', img: '☂️', d: '비 올 때 써' },
        { en: 'birthday', ko: '생일', img: '🎂', d: '내가 태어난 날이야' },
        { en: 'cake', ko: '케이크', img: '🍰', d: '달콤하고 부드러워', alt: ['cape', 'kate'] },
        { en: 'gift', ko: '선물', img: '🎁', d: '받으면 신나는 선물이야', alt: ['present'] },
        { en: 'bath', ko: '목욕', img: '🛁', d: '따뜻한 물에 몸을 씻어', alt: ['bass', 'path'] },
        { en: 'toothbrush', ko: '칫솔', img: '🪥', d: '이를 닦는 솔이야', alt: ['tooth brush'] },
        { en: 'cup', ko: '컵', img: '🥤', d: '물을 담아 마셔', alt: ['cop', 'cap'] },
      ],
      questions: [
        { q: "What's your name?", ko: '이름이 뭐야?', answer: 'My name is {NAME}.', keywords: ['yuni', 'yun', 'kim yun', 'yoon', 'uni', 'you knee', 'eunie', 'yuny', 'june'] },
        { q: 'How old are you?', ko: '몇 살이야?', answer: "I'm {AGE}.", keywords: ['six', 'seven', 'eight', '6', '7', '8', 'heaven', 'ate'] },
        { q: 'Nice to meet you!', ko: '만나서 반가워!', answer: 'Nice to meet you, too.', keywords: ['nice', 'meet', 'too', 'you too'] },
        { q: 'Are you a boy or a girl?', ko: '너는 남자아이야, 여자아이야?', img: '👦👧', answer: "I'm a boy.", keywords: ['boy', 'girl', 'boys'] },
        { q: 'Good morning!', ko: '좋은 아침!', img: '🌅', answer: 'Good morning!', keywords: ['morning', 'good morning'] },
        { q: 'Do you like school?', ko: '학교 좋아해?', img: '🏫', answer: 'Yes, I do.', keywords: ['yes', 'no', 'yeah', 'i do'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '✏️', answer: "It's a pencil.", keywords: ['pencil', 'pencils'] },
        { q: 'Thank you!', ko: '고마워!', img: '🙏', answer: "You're welcome.", keywords: ['welcome', "you're welcome", 'your welcome'] },
        { q: 'Who is your friend?', ko: '친구는 누구야?', answer: 'Eunhoo is my friend.', keywords: ['friend', 'friends', 'eunhoo', 'eun ho', 'unho', 'and who', 'in who'] },
        { q: "I'm sorry.", ko: '미안해.', img: '😔', answer: "That's okay.", keywords: ['okay', 'ok', "that's okay", 'alright', 'all right', 'fine'] },
        { q: 'Is this your bag?', ko: '이거 네 가방이야?', img: '🎒', answer: 'Yes, it is.', keywords: ['yes', 'no', 'yeah', 'it is'] },
        { q: "What's your favorite toy?", ko: '제일 좋아하는 장난감은 뭐야?', img: '🧸', answer: 'My favorite toy is a robot.', keywords: ['robot', 'car', 'ball', 'doll', 'game', 'teddy', 'bear', 'toy', 'dinosaur', 'blocks', 'truck', 'train'] },
        { q: 'Where do you sleep?', ko: '어디서 자?', img: '🛏️', answer: 'In my bed.', keywords: ['bed', 'bedroom', 'room'] },
        { q: 'Good night!', ko: '잘 자!', img: '🌙', answer: 'Good night!', keywords: ['night', 'good night', 'goodnight'] },
        { q: 'What color is your bag?', ko: '가방은 무슨 색이야?', img: '🎒', answer: "It's blue.", keywords: ['red', 'blue', 'yellow', 'green', 'black', 'white', 'pink', 'orange', 'purple', 'brown', 'gray', 'grey'] },
        { q: 'What do you wear on your feet?', ko: '발에는 뭘 신어?', img: '👟', answer: 'Shoes.', keywords: ['shoes', 'shoe', 'socks', 'sock'] },
        { q: 'Can I have a pencil, please?', ko: '연필 좀 줄래?', img: '✏️', answer: 'Here you are.', keywords: ['here', 'here you are', 'here you go', 'sure', 'okay', 'ok'] },
        { q: 'What time is it?', ko: '몇 시야?', img: '🕗', answer: "It's eight o'clock.", keywords: ['eight', '8', 'ate', "o'clock", 'oclock'] },
        { q: "What's in your bag?", ko: '가방에 뭐 있어?', img: '🎒📕', answer: 'A book.', keywords: ['book', 'books', 'pencil', 'notebook', 'crayon', 'crayons', 'toy', 'water'] },
        { q: 'Are you happy?', ko: '행복해?', img: '😊', answer: 'Yes, I am.', keywords: ['yes', 'yeah', 'i am', 'no'] },
      ],
    },
    {
      id: 'family', title: '가족과 친구', en: 'Family & Friends', icon: '🏡', sticker: '💞',
      words: [
        { en: 'mom', ko: '엄마', img: '👩', d: '우리 엄마야' },
        { en: 'dad', ko: '아빠', img: '👨', d: '우리 아빠야' },
        { en: 'brother', ko: '남자 형제', img: '👦', d: '형이나 남동생이야' },
        { en: 'sister', ko: '여자 형제', img: '👧', d: '누나나 여동생이야' },
        { en: 'baby', ko: '아기', img: '👶', d: '아주 어린 아기야' },
        { en: 'cousin', ko: '사촌', img: '🧒', d: '삼촌이나 이모네 아이, 사촌이야' },
        { en: 'grandma', ko: '할머니', img: '👵', d: '우리 할머니야' },
        { en: 'grandpa', ko: '할아버지', img: '👴', d: '우리 할아버지야' },
        { en: 'family', ko: '가족', img: '🏡', d: '함께 사는 우리 가족이야' },
        { en: 'love', ko: '사랑', img: '❤️', d: '좋아하는 마음, 사랑이야' },
        { en: 'uncle', ko: '삼촌', img: '🧔', d: '아빠나 엄마의 남자 형제야', alt: ['ankle'] },
        { en: 'aunt', ko: '이모·고모', img: '👩‍🦰', d: '엄마나 아빠의 여자 형제야', alt: ['ant', 'aunty', 'auntie'] },
        { en: 'hug', ko: '안아주기', img: '🤗', d: '꼭 안아주는 거야', alt: ['hugs', 'hog'] },
        { en: 'smile', ko: '미소', img: '😁', d: '방긋 웃는 얼굴이야' },
        { en: 'help', ko: '돕다', img: '🤝', d: '힘든 사람을 도와주는 거야' },
        { en: 'play', ko: '놀다', img: '🤹', d: '신나게 노는 거야' },
        { en: 'home', ko: '집', img: '🏠', d: '가족이 있는 우리 집이야' },
        { en: 'pet', ko: '반려동물', img: '🐕', d: '집에서 함께 사는 동물이야', alt: ['pat', 'pets'] },
        { en: 'dinner', ko: '저녁밥', img: '🍽️', d: '저녁에 먹는 밥이야' },
        { en: 'picture', ko: '사진·그림', img: '🖼️', d: '벽에 거는 사진이나 그림이야' },
        { en: 'party', ko: '파티', img: '🎉', d: '다 같이 모여 즐기는 거야' },
        { en: 'kiss', ko: '뽀뽀', img: '😘', d: '쪽 하고 뽀뽀해' },
        { en: 'cry', ko: '울다', img: '😭', d: '엉엉 우는 거야' },
        { en: 'laugh', ko: '웃다', img: '😂', d: '하하하 크게 웃는 거야', alt: ['laughs'] },
        { en: 'share', ko: '나누다', img: '🍪', d: '친구랑 나눠 먹는 거야', alt: ['chair'] },
        { en: 'hi', ko: '안녕', img: '🙋‍♀️', d: '짧게 하는 인사야', alt: ['high', 'hey'] },
        { en: 'together', ko: '함께', img: '👨‍👩‍👧', d: '다 같이 하는 거야' },
        { en: 'twins', ko: '쌍둥이', img: '👯', d: '똑같이 생긴 두 사람이야', alt: ['twin'] },
        { en: 'best friend', ko: '제일 친한 친구', img: '👭', d: '제일 친한 친구야', alt: ['best friends'] },
        { en: 'camera', ko: '사진기', img: '📷', d: '찰칵 사진을 찍어' },
        { en: 'song', ko: '노래', img: '🎵', d: '같이 부르는 노래야', alt: ['songs', 'some'] },
        { en: 'story', ko: '이야기', img: '📚', d: '재미있는 이야기책이야' },
        { en: 'letter', ko: '편지', img: '✉️', d: '마음을 적어서 보내' },
        { en: 'call', ko: '전화하다', img: '☎️', d: '따르릉 전화를 거는 거야', alt: ['cold', 'called'] },
        { en: 'kind', ko: '친절한', img: '😇', d: '다른 사람에게 착하게 해' },
        { en: 'funny', ko: '웃긴', img: '🤪', d: '재미있어서 웃음이 나' },
        { en: 'good', ko: '좋은', img: '👍', d: '잘했어, 좋아' },
        { en: 'bad', ko: '나쁜', img: '👎', d: '안 좋다는 말이야', alt: ['bed', 'bat'] },
        { en: 'old', ko: '나이 많은', img: '🧓', d: '나이가 많다는 말이야', alt: ['all', 'hold'] },
        { en: 'tall', ko: '키가 큰', img: '🦒', d: '키가 쑥 크다는 말이야', alt: ['toll', 'tell'] },
        { en: 'secret', ko: '비밀', img: '🤫', d: '쉿, 나만 아는 거야' },
        { en: 'surprise', ko: '깜짝 놀람', img: '😲', d: '깜짝 놀라게 하는 거야' },
        { en: 'promise', ko: '약속', img: '🤞', d: '꼭 지키기로 한 거야' },
        { en: 'clap', ko: '박수', img: '👏', d: '짝짝짝 손뼉을 쳐', alt: ['clapping', 'clip'] },
        { en: 'great', ko: '멋진', img: '🌟', d: '정말 잘했다는 말이야' },
        { en: 'welcome', ko: '환영해', img: '🙌', d: '반갑게 맞아주는 말이야' },
        { en: 'bedtime', ko: '잘 시간', img: '🛌', d: '이제 잘 시간이야', alt: ['bed time'] },
        { en: 'neighbor', ko: '이웃', img: '🏘️', d: '옆집에 사는 사람이야', alt: ['neighbour', 'neighbors'] },
        { en: 'people', ko: '사람들', img: '👥', d: '여러 사람을 말해' },
        { en: 'wedding', ko: '결혼식', img: '💒', d: '신랑 신부가 결혼하는 날이야' },
      ],
      questions: [
        { q: "Who's Hyun?", ko: '현이는 누구야?', answer: 'Hyun is my {HYUN_REL}.', keywords: ['brother', 'sister', 'brothers', 'sisters'], friend: 'hyun' },
        { q: "Who's Eunhoo?", ko: '은후는 누구야?', answer: 'Eunhoo is my friend.', keywords: ['friend', 'friends', 'fred'], friend: 'eunhoo' },
        { q: "Who's Chorok?", ko: '초록이는 누구야?', answer: 'Chorok is my cousin.', keywords: ['cousin', 'cousins', 'causing'], friend: 'chorok' },
        { q: "Who's this?", ko: '이 사람은 누구야?', img: '👩', answer: "It's my mom.", keywords: ['mom', 'mommy', 'mother', 'mum', 'mam'] },
        { q: "Who's this?", ko: '이 사람은 누구야?', img: '👨', answer: "It's my dad.", keywords: ['dad', 'daddy', 'father', 'that'] },
        { q: 'Do you want to play with me?', ko: '나랑 놀래?', answer: "Sure! Let's play.", keywords: ['sure', 'yes', 'okay', 'ok', "let's play", 'play', 'yeah'], friend: 'eunhoo' },
        { q: "Who's this?", ko: '이 사람은 누구야?', img: '👵', answer: "It's my grandma.", keywords: ['grandma', 'grandmother', 'granny', 'grandma s'] },
        { q: 'Do you love your family?', ko: '가족을 사랑해?', img: '🏡', answer: 'Yes, I do.', keywords: ['yes', 'yeah', 'i do', 'love'] },
        { q: 'How many people are in your family?', ko: '가족이 몇 명이야?', img: '👨‍👩‍👦‍👦', answer: 'Four.', keywords: ['two', 'three', 'four', 'five', 'six', '2', '3', '4', '5', '6', 'for', 'tree'] },
        { q: "Who's this?", ko: '이건 누구야?', img: '👶', answer: "It's a baby.", keywords: ['baby', 'babies'] },
        { q: 'Can you help me?', ko: '나 좀 도와줄래?', answer: 'Sure, I can help you.', keywords: ['sure', 'yes', 'okay', 'ok', 'help', 'yeah'], friend: 'hyun' },
        { q: 'Give me a hug!', ko: '안아줘!', img: '🤗', answer: 'Okay! Big hug!', keywords: ['okay', 'ok', 'hug', 'sure', 'yes'] },
        { q: 'Who do you play with?', ko: '누구랑 놀아?', answer: 'I play with my friends.', keywords: ['friend', 'friends', 'eunhoo', 'hyun', 'chorok', 'brother', 'sister', 'cousin', 'mom', 'dad'] },
        { q: 'Is Grandpa old or young?', ko: '할아버지는 나이가 많아, 적어?', img: '👴', answer: "He's old.", keywords: ['old', 'all', 'hold'] },
        { q: 'Do you have a brother?', ko: '남자 형제가 있어?', img: '👦', answer: 'Yes, I do.', keywords: ['yes', 'no', 'yeah', 'i do', "i don't"] },
        { q: 'Who cooks dinner?', ko: '저녁은 누가 해?', img: '🍽️', answer: 'My mom cooks dinner.', keywords: ['mom', 'dad', 'grandma', 'grandpa', 'mommy', 'daddy', 'me'] },
        { q: 'Say thank you to Mom!', ko: '엄마한테 고맙다고 말해봐!', img: '👩', answer: 'Thank you, Mom!', keywords: ['thank', 'thanks', 'thank you'] },
        { q: 'Who reads you a story?', ko: '누가 이야기책 읽어줘?', img: '📚', answer: 'My dad reads me a story.', keywords: ['dad', 'mom', 'daddy', 'mommy', 'grandma', 'grandpa', 'teacher'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🎉', answer: "It's a party!", keywords: ['party', 'parties'] },
        { q: "Say 'I love you' to Dad!", ko: '아빠한테 사랑한다고 말해봐!', img: '👨', answer: 'I love you, Dad!', keywords: ['love', 'love you'] },
      ],
    },
    {
      id: 'colors', title: '색깔과 숫자', en: 'Colors & Numbers', icon: '🎨', sticker: '🌈',
      words: [
        { en: 'red', ko: '빨간색', img: '🔴', d: '빨간 사과 같은 색이야' },
        { en: 'blue', ko: '파란색', img: '🔵', d: '파란 하늘 같은 색이야' },
        { en: 'yellow', ko: '노란색', img: '🟡', d: '노란 바나나 같은 색이야' },
        { en: 'green', ko: '초록색', img: '🟢', d: '나뭇잎 같은 색이야' },
        { en: 'one', ko: '하나', img: '1️⃣', alt: ['won', '1'], d: '하나, 숫자 일이야' },
        { en: 'two', ko: '둘', img: '2️⃣', alt: ['to', 'too', '2'], d: '둘, 숫자 이야' },
        { en: 'three', ko: '셋', img: '3️⃣', alt: ['tree', 'free', '3'], d: '셋, 숫자 삼이야' },
        { en: 'four', ko: '넷', img: '4️⃣', alt: ['for', '4'], d: '넷, 숫자 사야' },
        { en: 'five', ko: '다섯', img: '5️⃣', alt: ['5'], d: '다섯, 숫자 오야' },
        { en: 'ten', ko: '열', img: '🔟', alt: ['10', 'tan'], d: '열, 숫자 십이야' },
        { en: 'six', ko: '여섯', img: '6️⃣', alt: ['6', 'sicks', 'sex'], d: '여섯, 숫자 육이야' },
        { en: 'seven', ko: '일곱', img: '7️⃣', alt: ['7', 'heaven'], d: '일곱, 숫자 칠이야' },
        { en: 'eight', ko: '여덟', img: '8️⃣', alt: ['8', 'ate', 'hate'], d: '여덟, 숫자 팔이야' },
        { en: 'nine', ko: '아홉', img: '9️⃣', alt: ['9', 'nein', 'night'], d: '아홉, 숫자 구야' },
        { en: 'zero', ko: '영', img: '0️⃣', alt: ['0'], d: '하나도 없는 영이야' },
        { en: 'orange', ko: '주황색', img: '🟠', d: '귤 같은 색이야' },
        { en: 'purple', ko: '보라색', img: '🟣', d: '포도 같은 색이야' },
        { en: 'pink', ko: '분홍색', img: '🎀', d: '벚꽃 같은 색이야' },
        { en: 'brown', ko: '갈색', img: '🟤', d: '초콜릿 같은 색이야' },
        { en: 'black', ko: '검은색', img: '⚫', d: '까만 밤 같은 색이야', alt: ['block', 'back'] },
        { en: 'white', ko: '흰색', img: '⚪', d: '하얀 눈 같은 색이야', alt: ['right', 'wide'] },
        { en: 'color', ko: '색깔', img: '🎨', d: '빨주노초파남보, 색깔이야', alt: ['colour', 'colors'] },
        { en: 'circle', ko: '동그라미', img: '⭕', d: '동글동글 동그라미야' },
        { en: 'square', ko: '네모', img: '🟥', d: '반듯한 네모야' },
        { en: 'triangle', ko: '세모', img: '🔺', d: '뾰족한 세모야' },
        { en: 'star', ko: '별', img: '⭐', d: '반짝반짝 별 모양이야', alt: ['stars'] },
        { en: 'heart', ko: '하트', img: '💗', d: '사랑하는 마음 모양이야', alt: ['hurt', 'hard'] },
        { en: 'diamond', ko: '마름모', img: '🔷', d: '다이아몬드 모양이야' },
        { en: 'big', ko: '큰', img: '⬛', d: '커다랗다는 말이야', alt: ['bag', 'pig'] },
        { en: 'small', ko: '작은', img: '▪️', d: '조그맣다는 말이야', alt: ['smal', 'mall'] },
        { en: 'plus', ko: '더하기', img: '➕', d: '더하는 거야' },
        { en: 'minus', ko: '빼기', img: '➖', d: '빼는 거야' },
        { en: 'number', ko: '숫자', img: '🔢', d: '하나, 둘, 셋, 숫자야' },
        { en: 'count', ko: '세다', img: '🧮', d: '하나, 둘 세어 보는 거야' },
        { en: 'half', ko: '절반', img: '🌓', d: '반으로 나눈 거야', alt: ['have', 'health'] },
        { en: 'dice', ko: '주사위', img: '🎲', d: '던지면 숫자가 나와', alt: ['dies', 'nice'] },
        { en: 'light', ko: '밝은', img: '💡', d: '환하게 밝다는 말이야', alt: ['right', 'lite'] },
        { en: 'dark', ko: '어두운', img: '🌑', d: '깜깜하다는 말이야' },
        { en: 'eleven', ko: '열하나', img: '🕚', alt: ['11'], d: '열하나, 숫자 십일이야' },
        { en: 'twelve', ko: '열둘', img: '🕛', alt: ['12'], d: '열둘, 숫자 십이야' },
        { en: 'hundred', ko: '백', img: '💯', alt: ['100', 'one hundred'], d: '아주 큰 숫자, 백이야' },
        { en: 'first', ko: '첫 번째', img: '🥇', d: '맨 처음, 일등이야' },
        { en: 'gold', ko: '금색', img: '🪙', d: '반짝이는 금 색깔이야', alt: ['golden'] },
        { en: 'silver', ko: '은색', img: '🥈', d: '반짝이는 은 색깔이야' },
        { en: 'stripes', ko: '줄무늬', img: '🦓', d: '얼룩말 같은 줄무늬야', alt: ['stripe'] },
        { en: 'spots', ko: '점무늬', img: '🐆', d: '동글동글 점이 있어', alt: ['spot', 'dots'] },
        { en: 'paint', ko: '물감', img: '🖌️', d: '붓으로 색을 칠해', alt: ['paints', 'point'] },
        { en: 'bright', ko: '반짝이는', img: '🔆', d: '눈부시게 밝아', alt: ['right', 'bite'] },
        { en: 'many', ko: '많은', img: '🍬🍬🍬', d: '아주 많다는 말이야', alt: ['money', 'mini'] },
        { en: 'line', ko: '선', img: '〰️', d: '쭉 그은 선이야', alt: ['lion', 'lines'] },
      ],
      questions: [
        { q: 'What color is it?', ko: '이건 무슨 색이야?', img: '🔴', answer: "It's red.", keywords: ['red', 'read', 'rat'] },
        { q: 'How many ladybugs are there?', ko: '무당벌레가 몇 마리야?', img: '🐞🐞🐞', answer: 'Three.', keywords: ['three', '3', 'tree', 'free'] },
        { q: 'What color is it?', ko: '이건 무슨 색이야?', img: '🔵', answer: "It's blue.", keywords: ['blue', 'blew'] },
        { q: 'How many apples are there?', ko: '사과가 몇 개야?', img: '🍎🍎', answer: 'Two.', keywords: ['two', '2', 'to', 'too'] },
        { q: 'What color is it?', ko: '이건 무슨 색이야?', img: '🟡', answer: "It's yellow.", keywords: ['yellow'] },
        { q: 'What shape is it?', ko: '이건 무슨 모양이야?', img: '⭕', answer: "It's a circle.", keywords: ['circle', 'circles'] },
        { q: 'What color is it?', ko: '이건 무슨 색이야?', img: '🟢', answer: "It's green.", keywords: ['green', 'grin'] },
        { q: 'How many stars are there?', ko: '별이 몇 개야?', img: '⭐⭐⭐⭐⭐', answer: 'Five.', keywords: ['five', '5'] },
        { q: "What's your favorite color?", ko: '제일 좋아하는 색은 뭐야?', img: '🎨', answer: 'My favorite color is blue.', keywords: ['red', 'blue', 'yellow', 'green', 'black', 'white', 'pink', 'orange', 'purple', 'brown', 'gold', 'silver'] },
        { q: 'What shape is it?', ko: '이건 무슨 모양이야?', img: '🔺', answer: "It's a triangle.", keywords: ['triangle', 'triangles'] },
        { q: 'What number is it?', ko: '이건 무슨 숫자야?', img: '7️⃣', answer: 'Seven.', keywords: ['seven', '7', 'heaven'] },
        { q: 'What color is it?', ko: '이건 무슨 색이야?', img: '🍊', answer: "It's orange.", keywords: ['orange'] },
        { q: 'How many fish are there?', ko: '물고기가 몇 마리야?', img: '🐟🐟🐟🐟', answer: 'Four.', keywords: ['four', '4', 'for'] },
        { q: 'What shape is it?', ko: '이건 무슨 모양이야?', img: '⭐', answer: "It's a star.", keywords: ['star', 'stars'] },
        { q: 'Can you count to five?', ko: '다섯까지 셀 수 있어?', img: '🖐️', answer: 'One, two, three, four, five!', keywords: ['five', '5', 'four', 'three'] },
        { q: 'What color is it?', ko: '이건 무슨 색이야?', img: '🍇', answer: "It's purple.", keywords: ['purple', 'violet'] },
        { q: 'What number is it?', ko: '이건 무슨 숫자야?', img: '9️⃣', answer: 'Nine.', keywords: ['nine', '9', 'nein'] },
        { q: "What's one plus one?", ko: '1 더하기 1은?', img: '1️⃣➕1️⃣', answer: 'Two.', keywords: ['two', '2', 'to', 'too'] },
        { q: 'What colors is the panda?', ko: '판다는 무슨 색이야?', img: '🐼', answer: "It's black and white.", keywords: ['black', 'white'] },
        { q: 'How many legs does a dog have?', ko: '강아지는 다리가 몇 개야?', img: '🐶', answer: 'Four.', keywords: ['four', '4', 'for'] },
      ],
    },
    {
      id: 'insects', title: '곤충', en: 'Insects', icon: '🐞', sticker: '🦋', fav: true,
      words: [
        { en: 'ant', ko: '개미', img: '🐜', alt: ['aunt', 'and'], d: '줄지어 다니는 작은 곤충이야' },
        { en: 'bee', ko: '벌', img: '🐝', alt: ['b', 'be'], d: '꽃에서 꿀을 모아' },
        { en: 'butterfly', ko: '나비', img: '🦋', d: '예쁜 날개로 팔랑팔랑 날아' },
        { en: 'beetle', ko: '딱정벌레', img: '🪲', alt: ['beetles', 'beatle', 'beetle'], d: '딱딱한 날개를 가진 곤충이야' },
        { en: 'ladybug', ko: '무당벌레', img: '🐞', alt: ['lady bug'], d: '빨간 등에 까만 점이 있어' },
        { en: 'cricket', ko: '귀뚜라미', img: '🦗', d: '가을밤에 귀뚤귀뚤 울어' },
        { en: 'caterpillar', ko: '애벌레', img: '🐛', d: '나비가 되기 전 꼬물꼬물 애벌레야' },
        { en: 'mosquito', ko: '모기', img: '🦟', d: '윙윙 날아와서 물어' },
        { en: 'spider', ko: '거미', img: '🕷️', d: '줄을 치고 다리가 여덟 개야' },
        { en: 'bug', ko: '벌레', img: '🐜🐞', alt: ['bag', 'book'], d: '작은 벌레를 다 부르는 말이야' },
        { en: 'fly', ko: '파리', img: '🪰', alt: ['flies', 'fry'], d: '앵앵 날아다니는 파리야' },
        { en: 'worm', ko: '지렁이', img: '🪱', alt: ['warm', 'worms'], d: '흙 속에서 꿈틀꿈틀해' },
        { en: 'leaf', ko: '나뭇잎', img: '🍃', alt: ['leaves', 'life'], d: '애벌레가 좋아하는 잎이야' },
        { en: 'honey', ko: '꿀', img: '🍯', alt: ['funny'], d: '벌이 만든 달콤한 꿀이야' },
        { en: 'web', ko: '거미줄', img: '🕸️', alt: ['webs', 'wet'], d: '거미가 만든 줄이야' },
        { en: 'grass', ko: '풀', img: '🌿', alt: ['glass', 'grasses'], d: '풀밭에 곤충이 살아' },
        { en: 'look', ko: '보다', img: '👀', alt: ['luke', 'looking'], d: '눈으로 자세히 보는 거야' },
        { en: 'tiny', ko: '아주 작은', img: '🤏', alt: ['tiny tiny'], d: '아주아주 작다는 말이야' },
        { en: 'legs', ko: '다리들', img: '🦵', alt: ['leg', 'lacks'], d: '곤충은 다리가 여섯 개야' },
        { en: 'hide', ko: '숨다', img: '🙈', alt: ['hi', 'hides'], d: '안 보이게 숨는 거야' },
        { en: 'fast', ko: '빠른', img: '⚡', alt: ['first', 'fist'], d: '쌩하고 빠르다는 말이야' },
        { en: 'slow', ko: '느린', img: '🐢', alt: ['snow', 'flow'], d: '느릿느릿 느리다는 말이야' },
        { en: 'dig', ko: '땅을 파다', img: '⛏️', alt: ['big', 'deck'], d: '땅을 파는 거야' },
        { en: 'buzz', ko: '윙윙', img: '🐝🎵', alt: ['bus', 'buzzing'], d: '벌이 윙윙 나는 소리야' },
        { en: 'crawl', ko: '기어가다', img: '🐛💨', alt: ['call', 'crawling'], d: '엉금엉금 기어가는 거야' },
        { en: 'catch', ko: '잡다', img: '🥅', alt: ['cats', 'ketch'], d: '곤충을 잡는 거야' },
        { en: 'rock', ko: '돌', img: '🪨', alt: ['rocks', 'rack'], d: '돌 밑에 벌레가 숨어 있어' },
        { en: 'log', ko: '통나무', img: '🪵', alt: ['lock', 'logs'], d: '쓰러진 나무 기둥이야' },
        { en: 'hole', ko: '구멍', img: '🕳️', alt: ['whole', 'hold'], d: '개미가 드나드는 구멍이야' },
        { en: 'itchy', ko: '가려운', img: '😖', alt: ['itching', 'itch'], d: '모기에 물리면 가려워' },
        { en: 'scared', ko: '무서운', img: '😱', alt: ['scary', 'scare'], d: '무서워서 깜짝 놀랐어' },
        { en: 'yucky', ko: '으웩', img: '🤢', alt: ['yuck', 'yak'], d: '더럽고 싫다는 말이야' },
        { en: 'cute', ko: '귀여운', img: '🥰', alt: ['cut', 'cutie'], d: '작고 귀엽다는 말이야' },
        { en: 'cool', ko: '멋진', img: '😎', alt: ['cold', 'call'], d: '와, 멋지다는 말이야' },
        { en: 'insect', ko: '곤충', img: '🐝🦋', alt: ['insects', 'in sect'], d: '다리가 여섯 개인 벌레야' },
        { en: 'queen', ko: '여왕', img: '👑', alt: ['green', 'clean'], d: '여왕개미, 여왕벌이 있어' },
        { en: 'eggs', ko: '알', img: '🥚', alt: ['egg', 'x'], d: '곤충도 알을 낳아' },
        { en: 'night', ko: '밤', img: '🌃', alt: ['knight', 'nice'], d: '깜깜한 밤이야' },
        { en: 'box', ko: '상자', img: '📦', alt: ['books', 'fox'], d: '물건을 넣는 상자야' },
        { en: 'hungry', ko: '배고픈', img: '🤤', alt: ['angry'], d: '배가 꼬르륵 고파' },
        { en: 'sleep', ko: '자다', img: '💤', alt: ['sleeping', 'slip'], d: '쿨쿨 잠을 자' },
        { en: 'forest', ko: '숲', img: '🌲', alt: ['forests', 'for rest'], d: '나무가 많은 숲이야' },
        { en: 'wake up', ko: '일어나다', img: '🌄', alt: ['wake', 'awake'], d: '잠에서 깨는 거야' },
        { en: 'mushroom', ko: '버섯', img: '🍄', alt: ['mushrooms'], d: '우산처럼 생긴 버섯이야' },
        { en: 'daisy', ko: '데이지꽃', img: '🌼', alt: ['daisies', 'crazy'], d: '작고 노란 꽃이야' },
        { en: 'sunflower', ko: '해바라기', img: '🌻', alt: ['sun flower'], d: '해를 바라보는 큰 꽃이야' },
        { en: 'tulip', ko: '튤립', img: '🌷', alt: ['tulips', 'to lip'], d: '봄에 피는 예쁜 꽃이야' },
        { en: 'plant', ko: '식물', img: '🪴', alt: ['plants', 'planet'], d: '화분에서 자라는 식물이야' },
        { en: 'cockroach', ko: '바퀴벌레', img: '🪳', alt: ['roach', 'cock roach'], d: '어두운 곳에 숨는 벌레야' },
        { en: 'scorpion', ko: '전갈', img: '🦂', alt: ['scorpions'], d: '꼬리에 침이 있어' },
      ],
      questions: [
        { q: "What's this?", ko: '이건 뭐야?', img: '🪲', answer: "It's a beetle.", keywords: ['beetle', 'beetles', 'beatle'] },
        { q: 'Do you like bugs?', ko: '벌레 좋아해?', answer: 'Yes, I do.', keywords: ['yes', 'no', 'yeah', 'i do'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🐜', answer: "It's an ant.", keywords: ['ant', 'ants', 'aunt'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🦋', answer: "It's a butterfly.", keywords: ['butterfly', 'butterflies'] },
        { q: 'What color is the ladybug?', ko: '무당벌레는 무슨 색이야?', img: '🐞', answer: "It's red and black.", keywords: ['red', 'black'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🐝', answer: "It's a bee.", keywords: ['bee', 'bees', 'be', 'b'] },
        { q: 'Is the ant big or small?', ko: '개미는 커, 작아?', img: '🐜', answer: "It's small.", keywords: ['small', 'tiny', 'little', 'smal', 'mall'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🕷️', answer: "It's a spider.", keywords: ['spider', 'spiders'] },
        { q: 'Can a butterfly fly?', ko: '나비는 날 수 있어?', img: '🦋', answer: 'Yes, it can.', keywords: ['yes', 'yeah', 'it can', 'can'] },
        { q: 'What do bees make?', ko: '벌은 뭘 만들어?', img: '🐝', answer: 'Honey.', keywords: ['honey', 'funny'] },
        { q: 'How many legs does a spider have?', ko: '거미는 다리가 몇 개야?', img: '🕷️', answer: 'Eight.', keywords: ['eight', '8', 'ate'] },
        { q: 'What does a caterpillar become?', ko: '애벌레는 자라서 뭐가 돼?', img: '🐛', answer: 'A butterfly.', keywords: ['butterfly', 'butterflies'] },
        { q: 'Can an ant fly?', ko: '개미는 날 수 있어?', img: '🐜', answer: "No, it can't.", keywords: ['no', "can't", 'cannot', 'can not', 'nope'] },
        { q: 'Where is the bug?', ko: '벌레는 어디 있어?', img: '🐛🍃', answer: 'On the leaf.', keywords: ['leaf', 'leaves', 'life'] },
        { q: 'How many legs does an insect have?', ko: '곤충은 다리가 몇 개야?', img: '🐜', answer: 'Six.', keywords: ['six', '6', 'sicks', 'sex'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🦗', answer: "It's a cricket.", keywords: ['cricket', 'crickets'] },
        { q: 'Is the worm long or short?', ko: '지렁이는 길어, 짧아?', img: '🪱', answer: "It's long.", keywords: ['long', 'wrong', 'along'] },
        { q: 'Are you scared of bugs?', ko: '벌레가 무서워?', answer: "No, I'm not!", keywords: ['no', 'yes', 'not', "i'm not", 'yeah'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🦟', answer: "It's a mosquito.", keywords: ['mosquito', 'mosquitoes'] },
        { q: 'Do you like spiders?', ko: '거미 좋아해?', img: '🕷️', answer: "No, I don't.", keywords: ['yes', 'no', 'yeah', 'i do', "don't"] },
      ],
    },
    {
      id: 'sea', title: '물고기·바다생물', en: 'Sea Animals', icon: '🐟', sticker: '🐳', fav: true,
      words: [
        { en: 'fish', ko: '물고기', img: '🐟', d: '물속에서 헤엄쳐' },
        { en: 'shark', ko: '상어', img: '🦈', d: '이빨이 뾰족뾰족해' },
        { en: 'whale', ko: '고래', img: '🐳', alt: ['well', 'wail'], d: '바다에서 제일 커' },
        { en: 'octopus', ko: '문어', img: '🐙', d: '다리가 여덟 개야' },
        { en: 'crab', ko: '게', img: '🦀', d: '옆으로 걸어가' },
        { en: 'turtle', ko: '거북', img: '🐢', d: '등에 딱딱한 껍질이 있어' },
        { en: 'dolphin', ko: '돌고래', img: '🐬', d: '똑똑하고 점프를 잘해' },
        { en: 'shrimp', ko: '새우', img: '🦐', d: '몸이 동그랗게 굽었어' },
        { en: 'squid', ko: '오징어', img: '🦑', d: '다리가 열 개야' },
        { en: 'sea', ko: '바다', img: '🌊', alt: ['see', 'c'], d: '넓고 파란 바다야' },
        { en: 'seal', ko: '물범', img: '🦭', alt: ['seals', 'seel'], d: '바위 위에서 쉬는 물범이야' },
        { en: 'penguin', ko: '펭귄', img: '🐧', alt: ['penguins'], d: '뒤뚱뒤뚱 걷고 헤엄을 잘 쳐' },
        { en: 'shell', ko: '조개껍데기', img: '🐚', alt: ['shells', 'sell'], d: '바닷가에서 줍는 껍데기야' },
        { en: 'starfish', ko: '불가사리', img: '⭐', alt: ['star fish', 'star'], d: '별 모양 바다 친구야' },
        { en: 'lobster', ko: '바닷가재', img: '🦞', alt: ['lobsters'], d: '큰 집게가 있는 가재야' },
        { en: 'boat', ko: '보트', img: '🛶', alt: ['boats', 'both'], d: '노를 저어 가는 배야' },
        { en: 'island', ko: '섬', img: '🏝️', alt: ['islands', 'i land'], d: '바다 한가운데 있는 땅이야' },
        { en: 'sand', ko: '모래', img: '🏖️', alt: ['send', 'sent'], d: '바닷가의 보들보들 모래야' },
        { en: 'blowfish', ko: '복어', img: '🐡', alt: ['blow fish', 'puffer fish', 'pufferfish'], d: '화나면 몸이 빵빵해져' },
        { en: 'tropical fish', ko: '열대어', img: '🐠', alt: ['tropical'], d: '알록달록 예쁜 물고기야' },
        { en: 'otter', ko: '수달', img: '🦦', alt: ['other', 'otters'], d: '물에 누워 조개를 까먹어' },
        { en: 'oyster', ko: '굴', img: '🦪', alt: ['oysters'], d: '딱딱한 껍데기 속에 살아' },
        { en: 'surf', ko: '파도타기', img: '🏄', alt: ['surfing', 'serve'], d: '파도 위를 슝 타는 거야' },
        { en: 'fishing', ko: '낚시', img: '🎣', alt: ['fish in'], d: '물고기를 낚는 거야' },
        { en: 'dive', ko: '잠수하다', img: '🤿', alt: ['diving', 'five'], d: '물속으로 쏙 들어가' },
        { en: 'anchor', ko: '닻', img: '⚓', alt: ['anker'], d: '배가 떠내려가지 않게 해' },
        { en: 'pirate', ko: '해적', img: '🏴‍☠️', alt: ['pirates'], d: '보물을 찾는 해적이야' },
        { en: 'treasure', ko: '보물', img: '💎', alt: ['treasures'], d: '반짝반짝 귀한 보물이야' },
        { en: 'mermaid', ko: '인어', img: '🧜‍♀️', alt: ['mermaids'], d: '물고기 꼬리를 가진 인어야' },
        { en: 'teeth', ko: '이빨', img: '🦷', alt: ['tooth'], d: '상어는 이빨이 아주 많아' },
        { en: 'seaweed', ko: '미역', img: '🌿', alt: ['sea weed'], d: '바닷속에서 흔들흔들 자라' },
        { en: 'crocodile', ko: '악어', img: '🐊', alt: ['crocodiles', 'alligator'], d: '입이 크고 이빨이 많아' },
        { en: 'duck', ko: '오리', img: '🦆', alt: ['dock', 'ducks'], d: '꽥꽥 물 위에 둥둥 떠' },
        { en: 'swan', ko: '백조', img: '🦢', alt: ['swans', 'swim'], d: '목이 긴 하얀 새야' },
        { en: 'flamingo', ko: '홍학', img: '🦩', alt: ['flamingos'], d: '분홍색이고 한 발로 서' },
        { en: 'polar bear', ko: '북극곰', img: '🐻‍❄️', alt: ['polar', 'polar bears'], d: '얼음 나라의 하얀 곰이야' },
        { en: 'bucket', ko: '양동이', img: '🪣', alt: ['buckets', 'pocket'], d: '물이나 모래를 담아' },
        { en: 'castle', ko: '성', img: '🏰', alt: ['castles', 'sand castle'], d: '모래로 성을 쌓아' },
        { en: 'swimsuit', ko: '수영복', img: '🩱', alt: ['swim suit'], d: '수영할 때 입는 옷이야' },
        { en: 'goggles', ko: '물안경', img: '🥽', alt: ['goggle'], d: '물속에서 눈을 지켜줘' },
        { en: 'splash', ko: '첨벙', img: '💦', alt: ['splashing'], d: '물이 첨벙 튀는 거야' },
        { en: 'salty', ko: '짠', img: '🧂', alt: ['salt'], d: '바닷물은 짜' },
        { en: 'river', ko: '강', img: '🏞️', alt: ['rivers', 'liver'], d: '물이 흘러가는 강이야' },
        { en: 'ocean', ko: '대양', img: '🌊🌊', alt: ['oceans', 'motion'], d: '아주아주 넓은 바다야' },
        { en: 'hook', ko: '낚싯바늘', img: '🪝', alt: ['book', 'look'], d: '물고기를 잡는 바늘이야' },
        { en: 'net', ko: '그물', img: '🥅', alt: ['nut', 'neck'], d: '물고기를 잡는 그물이야' },
        { en: 'sunny', ko: '맑은', img: '🌞', alt: ['sonny', 'funny'], d: '해가 쨍쨍해' },
        { en: 'sail', ko: '돛단배', img: '⛵', alt: ['sale', 'sails'], d: '바람을 받아 가는 배야' },
        { en: 'sushi', ko: '초밥', img: '🍣', alt: ['sushis'], d: '생선을 올린 밥이야' },
        { en: 'wet', ko: '젖은', img: '💧', alt: ['what', 'web'], d: '물에 젖어서 축축해' },
      ],
      questions: [
        { q: 'Can fish swim?', ko: '물고기는 헤엄칠 수 있어?', img: '🐟', answer: 'Yes, they can.', keywords: ['yes', 'yeah', 'they can', 'can'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🐙', answer: "It's an octopus.", keywords: ['octopus', 'octopuses'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🦈', answer: "It's a shark.", keywords: ['shark', 'sharks'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🐢', answer: "It's a turtle.", keywords: ['turtle', 'turtles'] },
        { q: 'Is the whale big or small?', ko: '고래는 커, 작아?', img: '🐳', answer: "It's big.", keywords: ['big', 'huge', 'bag'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🦀', answer: "It's a crab.", keywords: ['crab', 'crabs', 'grab'] },
        { q: 'Where do fish live?', ko: '물고기는 어디 살아?', img: '🐟', answer: 'In the sea.', keywords: ['sea', 'see', 'water', 'ocean', 'river'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🐬', answer: "It's a dolphin.", keywords: ['dolphin', 'dolphins'] },
        { q: 'How many legs does an octopus have?', ko: '문어는 다리가 몇 개야?', img: '🐙', answer: 'Eight.', keywords: ['eight', '8', 'ate'] },
        { q: 'Can a turtle fly?', ko: '거북이는 날 수 있어?', img: '🐢', answer: "No, it can't.", keywords: ['no', "can't", 'cannot', 'can not', 'nope'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🐳', answer: "It's a whale.", keywords: ['whale', 'whales', 'well', 'wail'] },
        { q: 'What color is the sea?', ko: '바다는 무슨 색이야?', img: '🌊', answer: "It's blue.", keywords: ['blue', 'green', 'blew'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🐧', answer: "It's a penguin.", keywords: ['penguin', 'penguins'] },
        { q: 'Do you like the beach?', ko: '바닷가 좋아해?', img: '🏖️', answer: 'Yes, I do.', keywords: ['yes', 'no', 'yeah', 'i do'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🐚', answer: "It's a shell.", keywords: ['shell', 'shells', 'sell'] },
        { q: 'What do you see in the sea?', ko: '바다에서 뭐가 보여?', img: '🌊', answer: 'I see a fish.', keywords: ['fish', 'shark', 'whale', 'dolphin', 'crab', 'turtle', 'octopus', 'squid', 'shrimp', 'seal', 'boat', 'ship', 'shell'] },
        { q: 'Is the shark scary?', ko: '상어는 무서워?', img: '🦈', answer: "Yes, it's scary!", keywords: ['yes', 'no', 'scary', 'yeah'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🦭', answer: "It's a seal.", keywords: ['seal', 'seals'] },
        { q: 'Is the water cold?', ko: '물이 차가워?', img: '🌊', answer: "Yes, it's cold.", keywords: ['yes', 'no', 'cold', 'yeah'] },
        { q: 'Can a shark swim?', ko: '상어는 헤엄칠 수 있어?', img: '🦈', answer: 'Yes, it can.', keywords: ['yes', 'yeah', 'it can', 'can'] },
      ],
    },
    {
      id: 'body', title: '몸과 기분', en: 'Body & Feelings', icon: '🙂', sticker: '💪',
      words: [
        { en: 'eye', ko: '눈', img: '👁️', alt: ['i', 'eyes', 'hi'], d: '보는 곳이야' },
        { en: 'ear', ko: '귀', img: '👂', alt: ['here', 'year', 'ears'], d: '듣는 곳이야' },
        { en: 'nose', ko: '코', img: '👃', alt: ['knows', 'no'], d: '냄새 맡는 곳이야' },
        { en: 'mouth', ko: '입', img: '👄', d: '먹고 말하는 곳이야' },
        { en: 'hand', ko: '손', img: '✋', alt: ['hands'], d: '잡고 만지는 손이야' },
        { en: 'foot', ko: '발', img: '🦶', alt: ['feet', 'food'], d: '걷는 발이야' },
        { en: 'happy', ko: '행복한', img: '😊', d: '기분이 좋을 때 쓰는 말이야' },
        { en: 'sad', ko: '슬픈', img: '😢', alt: ['said'], d: '눈물이 날 것 같은 마음이야' },
        { en: 'angry', ko: '화난', img: '😠', d: '씩씩 화가 난 마음이야' },
        { en: 'sleepy', ko: '졸린', img: '😴', d: '하품이 나고 졸려' },
        { en: 'head', ko: '머리', img: '🙆', alt: ['had', 'bed'], d: '생각하는 머리야' },
        { en: 'hair', ko: '머리카락', img: '💇', alt: ['hare', 'air'], d: '머리에 난 머리카락이야' },
        { en: 'face', ko: '얼굴', img: '😶', alt: ['faces', 'phase'], d: '눈, 코, 입이 있는 얼굴이야' },
        { en: 'tooth', ko: '이', img: '🦷', alt: ['teeth', 'truth'], d: '음식을 씹는 이야' },
        { en: 'tongue', ko: '혀', img: '👅', alt: ['tong', 'young'], d: '맛을 느끼는 혀야' },
        { en: 'lips', ko: '입술', img: '💋', alt: ['lip', 'leaps'], d: '말랑말랑 입술이야' },
        { en: 'finger', ko: '손가락', img: '☝️', alt: ['fingers'], d: '손가락은 열 개야' },
        { en: 'thumb', ko: '엄지', img: '👍', alt: ['thumbs', 'some'], d: '최고! 엄지손가락이야' },
        { en: 'arm', ko: '팔', img: '💪', alt: ['arms', 'um'], d: '어깨에서 손까지야' },
        { en: 'leg', ko: '다리', img: '🦵', alt: ['legs', 'lake'], d: '걸을 때 쓰는 다리야' },
        { en: 'heart', ko: '심장', img: '🫀', alt: ['hard', 'hearts'], d: '쿵쿵 뛰는 심장이야' },
        { en: 'brain', ko: '뇌', img: '🧠', alt: ['rain', 'brains'], d: '생각하는 뇌야' },
        { en: 'bone', ko: '뼈', img: '🦴', alt: ['bones', 'born'], d: '몸을 받쳐주는 뼈야' },
        { en: 'nail', ko: '손톱', img: '💅', alt: ['nails', 'mail'], d: '손가락 끝의 손톱이야' },
        { en: 'scared', ko: '무서운', img: '😨', alt: ['scary', 'scare'], d: '무서워서 떨려' },
        { en: 'surprised', ko: '놀란', img: '😮', alt: ['surprise'], d: '깜짝 놀랐어' },
        { en: 'excited', ko: '신난', img: '🤩', alt: ['exciting'], d: '와, 너무 신나' },
        { en: 'tired', ko: '피곤한', img: '😩', alt: ['tire', 'tied'], d: '힘들고 피곤해' },
        { en: 'hungry', ko: '배고픈', img: '😋', alt: ['hunger'], d: '배가 꼬르륵 고파' },
        { en: 'thirsty', ko: '목마른', img: '🥤', alt: ['thirty', 'thursday'], d: '목이 말라서 물이 먹고 싶어' },
        { en: 'sick', ko: '아픈', img: '🤒', alt: ['six', 'seek'], d: '열이 나고 아파' },
        { en: 'hurt', ko: '다친', img: '🤕', alt: ['hurts'], d: '다쳐서 아파' },
        { en: 'hot', ko: '더운', img: '🥵', alt: ['hat', 'hut'], d: '더워서 땀이 나' },
        { en: 'cold', ko: '추운', img: '🥶', alt: ['called', 'code'], d: '추워서 덜덜 떨려' },
        { en: 'shy', ko: '부끄러운', img: '😳', alt: ['sky', 'shine'], d: '부끄러워서 얼굴이 빨개져' },
        { en: 'bored', ko: '심심한', img: '😑', alt: ['board', 'boring'], d: '할 게 없어서 심심해' },
        { en: 'silly', ko: '장난스러운', img: '😜', alt: ['sealy', 'really'], d: '장난치고 우스꽝스러워' },
        { en: 'worried', ko: '걱정되는', img: '😟', alt: ['worry', 'hurried'], d: '걱정이 돼' },
        { en: 'calm', ko: '차분한', img: '😌', alt: ['come', 'palm'], d: '마음이 편안하고 차분해' },
        { en: 'upset', ko: '속상한', img: '😣', alt: ['up set'], d: '속상하고 기분이 안 좋아' },
        { en: 'fine', ko: '괜찮은', img: '🙂', alt: ['find', 'fun'], d: '괜찮아, 좋아' },
        { en: 'laugh', ko: '웃다', img: '😆', alt: ['laughs', 'left'], d: '하하 웃는 거야' },
        { en: 'yawn', ko: '하품', img: '🥱', alt: ['yarn', 'young'], d: '졸려서 하아암 하품해' },
        { en: 'sneeze', ko: '재채기', img: '🤧', alt: ['sneezes', 'knees'], d: '에취! 재채기야' },
        { en: 'cough', ko: '기침', img: '😷', alt: ['cuff', 'coffee'], d: '콜록콜록 기침이야' },
        { en: 'wash', ko: '씻다', img: '🧼', alt: ['watch', 'washing'], d: '비누로 깨끗이 씻어' },
        { en: 'touch', ko: '만지다', img: '👆', alt: ['touching', 'much'], d: '손으로 만지는 거야' },
        { en: 'strong', ko: '힘센', img: '🏋️', alt: ['wrong', 'strongs'], d: '힘이 세다는 말이야' },
        { en: 'clean', ko: '깨끗한', img: '🚿', alt: ['green', 'queen'], d: '깨끗하게 씻었어' },
        { en: 'doctor', ko: '의사', img: '🧑‍⚕️', alt: ['doctors'], d: '아플 때 고쳐주는 분이야' },
      ],
      questions: [
        { q: 'How are you?', ko: '기분 어때?', answer: "I'm happy.", keywords: ['happy', 'good', 'fine', 'great', 'sleepy', 'hungry', 'sad', 'okay', 'ok', 'tired', 'angry'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '👃', answer: "It's my nose.", keywords: ['nose', 'knows', 'noes'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '👂', answer: "It's my ear.", keywords: ['ear', 'ears', 'here', 'year'] },
        { q: 'How many eyes do you have?', ko: '눈이 몇 개야?', img: '👀', answer: 'Two.', keywords: ['two', '2', 'to', 'too'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '👁️', answer: "It's my eye.", keywords: ['eye', 'eyes', 'i'] },
        { q: 'Are you hungry?', ko: '배고파?', img: '😋', answer: 'Yes, I am.', keywords: ['yes', 'no', 'yeah', 'i am', "i'm not"] },
        { q: 'How does he feel?', ko: '이 아이는 기분이 어때?', img: '😢', answer: "He's sad.", keywords: ['sad', 'said', 'crying'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '👄', answer: "It's my mouth.", keywords: ['mouth', 'mouse'] },
        { q: 'How many fingers do you have?', ko: '손가락이 몇 개야?', img: '🖐️🖐️', answer: 'Ten.', keywords: ['ten', '10', 'tan'] },
        { q: 'How does she feel?', ko: '이 아이는 기분이 어때?', img: '😠', answer: "She's angry.", keywords: ['angry', 'mad'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '✋', answer: "It's my hand.", keywords: ['hand', 'hands'] },
        { q: 'Are you sleepy?', ko: '졸려?', img: '😴', answer: "No, I'm not.", keywords: ['yes', 'no', 'yeah', 'i am', "i'm not"] },
        { q: 'What do you see with?', ko: '무엇으로 봐?', img: '👀', answer: 'My eyes.', keywords: ['eyes', 'eye', 'i'] },
        { q: 'How does he feel?', ko: '이 아이는 기분이 어때?', img: '😊', answer: "He's happy.", keywords: ['happy', 'good', 'glad'] },
        { q: 'What do you hear with?', ko: '무엇으로 들어?', img: '👂', answer: 'My ears.', keywords: ['ears', 'ear', 'here', 'years'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🦷', answer: "It's a tooth.", keywords: ['tooth', 'teeth', 'truth'] },
        { q: 'Are you sick?', ko: '아파?', img: '🤒', answer: "No, I'm fine.", keywords: ['no', 'fine', 'yes', 'okay', 'ok'] },
        { q: 'Touch your nose!', ko: '코를 만져봐!', img: '👃', answer: 'Okay! My nose!', keywords: ['okay', 'ok', 'nose', 'yes', 'here'] },
        { q: 'Are you tired?', ko: '피곤해?', img: '😩', answer: 'Yes, a little.', keywords: ['yes', 'no', 'little', 'yeah', "i'm not"] },
        { q: 'Wash your hands!', ko: '손 씻어!', img: '🧼', answer: 'Okay!', keywords: ['okay', 'ok', 'sure', 'yes', 'wash'] },
      ],
    },
    {
      id: 'living', title: '여러 가지 생물', en: 'Living Things', icon: '🌱', sticker: '🐸', fav: true,
      words: [
        { en: 'frog', ko: '개구리', img: '🐸', d: '폴짝폴짝 뛰어' },
        { en: 'snake', ko: '뱀', img: '🐍', d: '스르르 기어가' },
        { en: 'bird', ko: '새', img: '🐦', d: '하늘을 날아' },
        { en: 'rabbit', ko: '토끼', img: '🐰', d: '귀가 길고 깡충깡충 뛰어' },
        { en: 'dog', ko: '개', img: '🐶', d: '멍멍 짖어' },
        { en: 'cat', ko: '고양이', img: '🐱', d: '야옹 하고 울어' },
        { en: 'lion', ko: '사자', img: '🦁', d: '멋진 갈기가 있는 동물의 왕이야' },
        { en: 'tree', ko: '나무', img: '🌳', d: '키가 크고 잎이 많아' },
        { en: 'flower', ko: '꽃', img: '🌸', d: '예쁘게 피어' },
        { en: 'snail', ko: '달팽이', img: '🐌', d: '집을 등에 지고 다녀' },
        { en: 'bear', ko: '곰', img: '🐻', alt: ['bears', 'bare', 'beer'], d: '크고 힘센 곰이야' },
        { en: 'tiger', ko: '호랑이', img: '🐯', alt: ['tigers'], d: '줄무늬가 있는 어흥 호랑이야' },
        { en: 'elephant', ko: '코끼리', img: '🐘', alt: ['elephants'], d: '코가 아주 길어' },
        { en: 'monkey', ko: '원숭이', img: '🐵', alt: ['monkeys'], d: '나무를 잘 타고 바나나를 좋아해' },
        { en: 'horse', ko: '말', img: '🐴', alt: ['horses', 'house'], d: '히히힝 빨리 달려' },
        { en: 'cow', ko: '소', img: '🐮', alt: ['cows', 'call'], d: '음메 하고 우유를 줘' },
        { en: 'pig', ko: '돼지', img: '🐷', alt: ['pigs', 'big'], d: '꿀꿀 코가 동그래' },
        { en: 'sheep', ko: '양', img: '🐑', alt: ['ship', 'cheap'], d: '털이 복슬복슬해' },
        { en: 'chicken', ko: '닭', img: '🐔', alt: ['chickens', 'kitchen'], d: '꼬끼오 알을 낳아' },
        { en: 'chick', ko: '병아리', img: '🐤', alt: ['check', 'chicks'], d: '삐약삐약 작은 병아리야' },
        { en: 'mouse', ko: '쥐', img: '🐭', alt: ['mice', 'mouth'], d: '찍찍 작은 쥐야' },
        { en: 'hamster', ko: '햄스터', img: '🐹', alt: ['hamsters'], d: '볼에 먹이를 가득 넣어' },
        { en: 'puppy', ko: '강아지', img: '🐕', alt: ['puppies', 'poppy'], d: '아기 개, 강아지야' },
        { en: 'kitten', ko: '아기 고양이', img: '🐈', alt: ['kittens', 'kitty'], d: '아기 고양이야' },
        { en: 'owl', ko: '부엉이', img: '🦉', alt: ['owls', 'all'], d: '밤에 부엉부엉 울어' },
        { en: 'eagle', ko: '독수리', img: '🦅', alt: ['eagles', 'legal'], d: '하늘 높이 나는 큰 새야' },
        { en: 'parrot', ko: '앵무새', img: '🦜', alt: ['parrots', 'carrot'], d: '말을 따라 하는 새야' },
        { en: 'fox', ko: '여우', img: '🦊', alt: ['fax', 'box'], d: '꼬리가 복슬복슬한 여우야' },
        { en: 'wolf', ko: '늑대', img: '🐺', alt: ['wolves', 'woof'], d: '아우우 우는 늑대야' },
        { en: 'deer', ko: '사슴', img: '🦌', alt: ['dear', 'dare'], d: '뿔이 멋진 사슴이야' },
        { en: 'squirrel', ko: '다람쥐', img: '🐿️', alt: ['squirrels'], d: '도토리를 모아' },
        { en: 'panda', ko: '판다', img: '🐼', alt: ['pandas'], d: '대나무를 먹는 흑백 곰이야' },
        { en: 'koala', ko: '코알라', img: '🐨', alt: ['koalas', 'cola'], d: '나무에 매달려 자' },
        { en: 'kangaroo', ko: '캥거루', img: '🦘', alt: ['kangaroos'], d: '주머니에 아기를 넣고 뛰어' },
        { en: 'giraffe', ko: '기린', img: '🦒', alt: ['giraffes'], d: '목이 아주 길어' },
        { en: 'zebra', ko: '얼룩말', img: '🦓', alt: ['zebras'], d: '까만 줄무늬 말이야' },
        { en: 'camel', ko: '낙타', img: '🐫', alt: ['camels', 'cable'], d: '등에 혹이 있어' },
        { en: 'hippo', ko: '하마', img: '🦛', alt: ['hippos', 'hippopotamus'], d: '입이 아주 커' },
        { en: 'gorilla', ko: '고릴라', img: '🦍', alt: ['gorillas'], d: '가슴을 쿵쿵 쳐' },
        { en: 'bat', ko: '박쥐', img: '🦇', alt: ['bad', 'bats'], d: '밤에 날아다녀' },
        { en: 'hedgehog', ko: '고슴도치', img: '🦔', alt: ['hedgehogs'], d: '등에 가시가 뾰족뾰족해' },
        { en: 'lizard', ko: '도마뱀', img: '🦎', alt: ['lizards'], d: '벽을 기어올라' },
        { en: 'dinosaur', ko: '공룡', img: '🦖', alt: ['dinosaurs'], d: '아주 옛날에 살았던 공룡이야' },
        { en: 'dragon', ko: '용', img: '🐉', alt: ['dragons', 'wagon'], d: '이야기 속에 나오는 용이야' },
        { en: 'unicorn', ko: '유니콘', img: '🦄', alt: ['unicorns'], d: '뿔이 하나 있는 상상의 말이야' },
        { en: 'rhino', ko: '코뿔소', img: '🦏', alt: ['rhinos', 'rhinoceros'], d: '코에 큰 뿔이 있어' },
        { en: 'goat', ko: '염소', img: '🐐', alt: ['goats', 'coat'], d: '음매 수염이 있어' },
        { en: 'cactus', ko: '선인장', img: '🌵', alt: ['cactuses'], d: '가시가 있고 사막에 살아' },
        { en: 'rose', ko: '장미', img: '🌹', alt: ['roses', 'rows'], d: '빨갛고 향기로운 꽃이야' },
        { en: 'seed', ko: '씨앗', img: '🌱', alt: ['seeds', 'seat'], d: '땅에 심으면 싹이 나' },
      ],
      questions: [
        { q: 'Is it big or small?', ko: '이건 커, 작아?', img: '🐌', answer: "It's small.", keywords: ['small', 'smal', 'mall'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🐸', answer: "It's a frog.", keywords: ['frog', 'frogs', 'frock'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🐶', answer: "It's a dog.", keywords: ['dog', 'dogs', 'puppy'] },
        { q: 'What does a dog say?', ko: '강아지는 뭐라고 짖어?', img: '🐶', answer: 'Woof woof!', keywords: ['woof', 'bark', 'wolf', 'ruff', 'bow wow', 'wolf wolf'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🐱', answer: "It's a cat.", keywords: ['cat', 'cats', 'kitty'] },
        { q: 'What does a cat say?', ko: '고양이는 뭐라고 울어?', img: '🐱', answer: 'Meow!', keywords: ['meow', 'mew', 'me out', 'miaow'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🐰', answer: "It's a rabbit.", keywords: ['rabbit', 'bunny', 'rabbits'] },
        { q: 'Can a bird fly?', ko: '새는 날 수 있어?', img: '🐦', answer: 'Yes, it can.', keywords: ['yes', 'yeah', 'it can', 'can'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🦁', answer: "It's a lion.", keywords: ['lion', 'lions'] },
        { q: 'Is the elephant big or small?', ko: '코끼리는 커, 작아?', img: '🐘', answer: "It's big.", keywords: ['big', 'huge', 'bag'] },
        { q: 'What color is the frog?', ko: '개구리는 무슨 색이야?', img: '🐸', answer: "It's green.", keywords: ['green', 'grin'] },
        { q: 'What does a cow say?', ko: '소는 뭐라고 울어?', img: '🐮', answer: 'Moo!', keywords: ['moo', 'move', 'mu', 'moon'] },
        { q: 'Can a snake walk?', ko: '뱀은 걸을 수 있어?', img: '🐍', answer: "No, it can't.", keywords: ['no', "can't", 'cannot', 'can not', 'nope'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🌸', answer: "It's a flower.", keywords: ['flower', 'flowers'] },
        { q: 'Where do birds live?', ko: '새는 어디 살아?', img: '🐦', answer: 'In a tree.', keywords: ['tree', 'trees', 'nest', 'sky'] },
        { q: 'Is the rabbit fast or slow?', ko: '토끼는 빨라, 느려?', img: '🐰', answer: "It's fast.", keywords: ['fast', 'first'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🦖', answer: "It's a dinosaur.", keywords: ['dinosaur', 'dinosaurs', 't rex'] },
        { q: 'Do you have a pet?', ko: '반려동물 있어?', img: '🐕', answer: "No, I don't.", keywords: ['yes', 'no', 'yeah', 'i do', "don't"] },
        { q: 'Is the snail fast or slow?', ko: '달팽이는 빨라, 느려?', img: '🐌', answer: "It's slow.", keywords: ['slow', 'snow', 'flow'] },
        { q: 'What animal do you like?', ko: '어떤 동물을 좋아해?', answer: 'I like dinosaurs.', keywords: ['dog', 'dogs', 'cat', 'cats', 'dinosaur', 'dinosaurs', 'lion', 'tiger', 'rabbit', 'bear', 'frog', 'snake', 'bird', 'fish', 'shark', 'whale', 'monkey', 'elephant', 'panda', 'beetle', 'bugs', 'animals', 'penguin', 'dolphin'] },
      ],
    },
    {
      id: 'food', title: '음식', en: 'Food', icon: '🍎', sticker: '🍕',
      words: [
        { en: 'apple', ko: '사과', img: '🍎', d: '빨갛고 아삭해' },
        { en: 'banana', ko: '바나나', img: '🍌', d: '길고 노래' },
        { en: 'grape', ko: '포도', img: '🍇', alt: ['grapes'], d: '알알이 달려 있어' },
        { en: 'strawberry', ko: '딸기', img: '🍓', d: '빨갛고 새콤달콤해' },
        { en: 'pizza', ko: '피자', img: '🍕', d: '동그랗고 치즈가 쭉 늘어나' },
        { en: 'milk', ko: '우유', img: '🥛', d: '하얗고 고소해' },
        { en: 'egg', ko: '달걀', img: '🥚', d: '닭이 낳았어' },
        { en: 'bread', ko: '빵', img: '🍞', d: '폭신폭신해' },
        { en: 'rice', ko: '밥', img: '🍚', alt: ['nice', 'lice'], d: '매일 먹는 밥이야' },
        { en: 'water', ko: '물', img: '💧', d: '목마를 때 마셔' },
        { en: 'orange', ko: '오렌지', img: '🍊', alt: ['oranges'], d: '새콤달콤 동그란 과일이야' },
        { en: 'watermelon', ko: '수박', img: '🍉', alt: ['water melon'], d: '여름에 먹는 커다란 과일이야' },
        { en: 'lemon', ko: '레몬', img: '🍋', alt: ['lemons', 'lemmon'], d: '아주 시큼해' },
        { en: 'peach', ko: '복숭아', img: '🍑', alt: ['peaches', 'beach'], d: '말랑말랑 달콤해' },
        { en: 'cherry', ko: '체리', img: '🍒', alt: ['cherries', 'sherry'], d: '작고 빨간 열매 두 개야' },
        { en: 'carrot', ko: '당근', img: '🥕', alt: ['carrots', 'karat', 'parrot'], d: '토끼가 좋아하는 주황 채소야' },
        { en: 'corn', ko: '옥수수', img: '🌽', alt: ['con', 'cone'], d: '노란 알이 촘촘해' },
        { en: 'potato', ko: '감자', img: '🥔', alt: ['potatoes'], d: '땅속에서 자라는 감자야' },
        { en: 'tomato', ko: '토마토', img: '🍅', alt: ['tomatoes'], d: '빨갛고 동그란 채소야' },
        { en: 'cheese', ko: '치즈', img: '🧀', alt: ['cheeses', 'chips'], d: '노랗고 고소해' },
        { en: 'cookie', ko: '쿠키', img: '🍪', alt: ['cookies'], d: '바삭바삭 과자야' },
        { en: 'candy', ko: '사탕', img: '🍬', alt: ['candies', 'can dee'], d: '입에서 사르르 녹아' },
        { en: 'ice cream', ko: '아이스크림', img: '🍦', alt: ['icecream', 'i scream'], d: '차갑고 달콤해' },
        { en: 'chocolate', ko: '초콜릿', img: '🍫', alt: ['chocolates'], d: '달콤한 갈색 과자야' },
        { en: 'juice', ko: '주스', img: '🧃', alt: ['juices', 'use'], d: '과일로 만든 음료야' },
        { en: 'hamburger', ko: '햄버거', img: '🍔', alt: ['burger', 'hamburgers'], d: '빵 사이에 고기가 있어' },
        { en: 'hot dog', ko: '핫도그', img: '🌭', alt: ['hotdog'], d: '빵 사이에 소시지가 있어' },
        { en: 'noodles', ko: '국수', img: '🍜', alt: ['noodle'], d: '후루룩 먹는 국수야' },
        { en: 'soup', ko: '국', img: '🍲', alt: ['soap', 'super'], d: '따뜻한 국물이야' },
        { en: 'sandwich', ko: '샌드위치', img: '🥪', alt: ['sandwiches'], d: '빵 사이에 채소랑 햄이 있어' },
        { en: 'salad', ko: '샐러드', img: '🥗', alt: ['salads', 'solid'], d: '채소를 섞은 음식이야' },
        { en: 'donut', ko: '도넛', img: '🍩', alt: ['doughnut', 'donuts'], d: '가운데 구멍이 뚫렸어' },
        { en: 'popcorn', ko: '팝콘', img: '🍿', alt: ['pop corn'], d: '톡톡 튀긴 옥수수야' },
        { en: 'pancake', ko: '팬케이크', img: '🥞', alt: ['pancakes'], d: '납작하고 폭신한 빵이야' },
        { en: 'meat', ko: '고기', img: '🍖', alt: ['meet', 'mit'], d: '힘이 나는 고기야' },
        { en: 'chicken', ko: '치킨', img: '🍗', alt: ['kitchen', 'chickens'], d: '바삭바삭 닭고기야' },
        { en: 'fries', ko: '감자튀김', img: '🍟', alt: ['french fries', 'fry', 'price'], d: '길쭉한 감자튀김이야' },
        { en: 'broccoli', ko: '브로콜리', img: '🥦', alt: ['brocoli'], d: '작은 나무처럼 생긴 채소야' },
        { en: 'cucumber', ko: '오이', img: '🥒', alt: ['cucumbers'], d: '길고 시원한 초록 채소야' },
        { en: 'onion', ko: '양파', img: '🧅', alt: ['onions', 'union'], d: '자르면 눈물이 나' },
        { en: 'pear', ko: '배', img: '🍐', alt: ['pair', 'bear'], d: '시원하고 달콤한 과일이야' },
        { en: 'pineapple', ko: '파인애플', img: '🍍', alt: ['pine apple'], d: '겉은 뾰족 속은 노래' },
        { en: 'melon', ko: '멜론', img: '🍈', alt: ['melons'], d: '초록색 달콤한 과일이야' },
        { en: 'kiwi', ko: '키위', img: '🥝', alt: ['kiwis'], d: '겉은 털이 있고 속은 초록이야' },
        { en: 'butter', ko: '버터', img: '🧈', alt: ['better', 'batter'], d: '빵에 발라 먹어' },
        { en: 'spoon', ko: '숟가락', img: '🥄', alt: ['spoons', 'soon'], d: '밥이랑 국을 떠먹어' },
        { en: 'fork', ko: '포크', img: '🍴', alt: ['forks', 'folk'], d: '콕 찍어서 먹어' },
        { en: 'dumpling', ko: '만두', img: '🥟', alt: ['dumplings'], d: '속이 꽉 찬 만두야' },
        { en: 'rice ball', ko: '주먹밥', img: '🍙', alt: ['riceball', 'rice balls'], d: '동그랗게 뭉친 밥이야' },
        { en: 'lollipop', ko: '막대사탕', img: '🍭', alt: ['lollipops', 'lolly pop'], d: '막대에 달린 동그란 사탕이야' },
      ],
      questions: [
        { q: 'Do you like pizza?', ko: '피자 좋아해?', img: '🍕', answer: 'Yes, I do.', keywords: ['yes', 'no', 'yeah', 'i do'] },
        { q: 'What would you like?', ko: '뭐 먹고 싶어?', img: '🍓', answer: 'Strawberries, please.', keywords: ['strawberry', 'strawberries'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🍌', answer: "It's a banana.", keywords: ['banana', 'bananas'] },
        { q: 'Would you like some milk?', ko: '우유 마실래?', img: '🥛', answer: 'Yes, please.', keywords: ['yes', 'please', 'no', 'thank you', 'thanks', 'yeah'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🍎', answer: "It's an apple.", keywords: ['apple', 'apples'] },
        { q: 'What color is the banana?', ko: '바나나는 무슨 색이야?', img: '🍌', answer: "It's yellow.", keywords: ['yellow'] },
        { q: 'How many cookies are there?', ko: '쿠키가 몇 개야?', img: '🍪🍪🍪', answer: 'Three.', keywords: ['three', '3', 'tree', 'free'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🍉', answer: "It's a watermelon.", keywords: ['watermelon', 'water melon', 'watermelons'] },
        { q: 'Is ice cream hot or cold?', ko: '아이스크림은 뜨거워, 차가워?', img: '🍦', answer: "It's cold.", keywords: ['cold', 'cool', 'called', 'code'] },
        { q: 'What do you want for lunch?', ko: '점심 뭐 먹을래?', img: '🍽️', answer: 'I want pizza.', keywords: ['pizza', 'rice', 'noodles', 'hamburger', 'burger', 'chicken', 'bread', 'sandwich', 'soup', 'kimchi', 'egg', 'eggs', 'fish', 'meat', 'dumplings', 'hot dog', 'spaghetti', 'pasta'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🥕', answer: "It's a carrot.", keywords: ['carrot', 'carrots', 'karat', 'parrot'] },
        { q: 'Is the soup hot or cold?', ko: '국은 뜨거워, 차가워?', img: '🍲', answer: "It's hot.", keywords: ['hot', 'hat', 'hut'] },
        { q: 'Is it sweet?', ko: '이거 달아?', img: '🍫', answer: "Yes, it's sweet!", keywords: ['yes', 'sweet', 'yeah'] },
        { q: 'Do you like carrots?', ko: '당근 좋아해?', img: '🥕', answer: "No, I don't.", keywords: ['yes', 'no', 'yeah', 'i do', "don't"] },
        { q: 'What do you drink?', ko: '뭐 마셔?', img: '🥤', answer: 'I drink water.', keywords: ['water', 'milk', 'juice', 'tea'] },
        { q: "What's your favorite fruit?", ko: '제일 좋아하는 과일은 뭐야?', img: '🍓🍉', answer: 'I like strawberries.', keywords: ['apple', 'apples', 'banana', 'bananas', 'grape', 'grapes', 'strawberry', 'strawberries', 'orange', 'oranges', 'watermelon', 'peach', 'cherry', 'cherries', 'pear', 'kiwi', 'melon', 'pineapple', 'mango'] },
        { q: "What's for breakfast?", ko: '아침은 뭐 먹어?', img: '🍳', answer: 'Eggs and bread.', keywords: ['egg', 'eggs', 'bread', 'rice', 'milk', 'cereal', 'toast', 'pancake', 'pancakes', 'soup', 'fruit'] },
        { q: 'Is it yummy?', ko: '맛있어?', img: '😋', answer: "Yes, it's yummy!", keywords: ['yes', 'yummy', 'good', 'delicious', 'yeah'] },
        { q: 'Can I have some, please?', ko: '나도 조금 줄래?', img: '🍩', answer: 'Sure, here you are.', keywords: ['sure', 'here', 'okay', 'ok', 'yes'] },
        { q: 'Do you like kimchi?', ko: '김치 좋아해?', answer: 'Yes, I do.', keywords: ['yes', 'no', 'yeah', 'i do', "don't"] },
      ],
    },
    {
      id: 'robots', title: '로봇', en: 'Robots', icon: '🤖', sticker: '🚀', fav: true,
      words: [
        { en: 'robot', ko: '로봇', img: '🤖', d: '움직이는 기계 친구야' },
        { en: 'battery', ko: '배터리', img: '🔋', d: '힘을 주는 전지야' },
        { en: 'button', ko: '버튼', img: '🔘', d: '꾹 누르는 거야' },
        { en: 'gear', ko: '톱니바퀴', img: '⚙️', d: '빙글빙글 도는 바퀴야' },
        { en: 'computer', ko: '컴퓨터', img: '💻', d: '생각하고 계산하는 기계야' },
        { en: 'rocket', ko: '로켓', img: '🚀', d: '우주로 슝 날아가' },
        { en: 'arm', ko: '팔', img: '💪', d: '어깨에서 손까지야' },
        { en: 'leg', ko: '다리', img: '🦵', d: '걸을 때 쓰는 다리야' },
        { en: 'walk', ko: '걷다', img: '🚶', alt: ['work', 'woke'], d: '뚜벅뚜벅 걷는 거야' },
        { en: 'stop', ko: '멈추다', img: '🛑', d: '그 자리에 멈추는 거야' },
        { en: 'light', ko: '불빛', img: '💡', alt: ['lights', 'lite'], d: '반짝 켜지는 불빛이야' },
        { en: 'screen', ko: '화면', img: '🖥️', alt: ['screens', 'scream'], d: '그림이 나오는 화면이야' },
        { en: 'up', ko: '위로', img: '⬆️', alt: ['app', 'op'], d: '위로 올라가' },
        { en: 'down', ko: '아래로', img: '⬇️', alt: ['town', 'done'], d: '아래로 내려가' },
        { en: 'left', ko: '왼쪽', img: '⬅️', alt: ['lift', 'laughed'], d: '왼쪽으로 가' },
        { en: 'right', ko: '오른쪽', img: '➡️', alt: ['write', 'ride', 'white'], d: '오른쪽으로 가' },
        { en: 'moon', ko: '달', img: '🌕', alt: ['moons', 'noon'], d: '밤하늘의 동그란 달이야' },
        { en: 'space', ko: '우주', img: '🌌', alt: ['spaces', 'spice'], d: '별들이 가득한 우주야' },
        { en: 'planet', ko: '행성', img: '🪐', alt: ['planets', 'plant'], d: '고리가 있는 토성 같은 행성이야' },
        { en: 'earth', ko: '지구', img: '🌍', alt: ['the earth', 'worth'], d: '우리가 사는 지구야' },
        { en: 'alien', ko: '외계인', img: '👽', alt: ['aliens'], d: '우주에서 온 친구야' },
        { en: 'UFO', ko: '비행접시', img: '🛸', alt: ['ufo', 'u f o', 'you f o'], d: '외계인이 타는 비행접시야' },
        { en: 'astronaut', ko: '우주비행사', img: '🧑‍🚀', alt: ['astronauts'], d: '우주에 가는 사람이야' },
        { en: 'satellite', ko: '인공위성', img: '🛰️', alt: ['satellites'], d: '지구 주위를 빙빙 돌아' },
        { en: 'antenna', ko: '안테나', img: '📡', alt: ['antennas'], d: '신호를 받아' },
        { en: 'keyboard', ko: '키보드', img: '⌨️', alt: ['key board'], d: '글자를 톡톡 쳐' },
        { en: 'mouse', ko: '마우스', img: '🖱️', alt: ['mouth', 'mice'], d: '컴퓨터에서 딸깍 눌러' },
        { en: 'plug', ko: '플러그', img: '🔌', alt: ['plugs', 'blog'], d: '콘센트에 꽂아' },
        { en: 'power', ko: '전기', img: '⚡', alt: ['powers', 'flower'], d: '기계를 움직이는 힘이야' },
        { en: 'tools', ko: '공구', img: '🧰', alt: ['tool', 'fools'], d: '고칠 때 쓰는 도구 상자야' },
        { en: 'hammer', ko: '망치', img: '🔨', alt: ['hammers'], d: '쾅쾅 못을 박아' },
        { en: 'screwdriver', ko: '드라이버', img: '🪛', alt: ['screw driver', 'driver'], d: '나사를 돌려' },
        { en: 'wrench', ko: '스패너', img: '🔧', alt: ['ranch', 'french'], d: '볼트를 꽉 조여' },
        { en: 'bolt', ko: '볼트', img: '🔩', alt: ['bolts', 'boat'], d: '로봇을 조립하는 나사야' },
        { en: 'saw', ko: '톱', img: '🪚', alt: ['so', 'sore'], d: '나무를 쓱싹 잘라' },
        { en: 'turn', ko: '돌다', img: '🔄', alt: ['turns', 'tern'], d: '빙글 도는 거야' },
        { en: 'start', ko: '시작', img: '▶️', alt: ['starts', 'star'], d: '이제 시작해' },
        { en: 'beep', ko: '삐 소리', img: '🔊', alt: ['beeps', 'bee'], d: '삐빅 로봇 소리야' },
        { en: 'talk', ko: '말하다', img: '💬', alt: ['talking', 'took'], d: '이야기하는 거야' },
        { en: 'think', ko: '생각하다', img: '🤔', alt: ['thing', 'sink'], d: '곰곰이 생각하는 거야' },
        { en: 'build', ko: '만들다', img: '🏗️', alt: ['built', 'building'], d: '뚝딱뚝딱 만드는 거야' },
        { en: 'fix', ko: '고치다', img: '🛠️', alt: ['fixed', 'fox'], d: '고장 난 걸 고쳐' },
        { en: 'blocks', ko: '블록', img: '🧱', alt: ['block', 'blox'], d: '쌓아서 만드는 블록이야' },
        { en: 'printer', ko: '프린터', img: '🖨️', alt: ['printers'], d: '종이에 그림을 뽑아' },
        { en: 'joystick', ko: '조종기', img: '🕹️', alt: ['joy stick'], d: '로봇을 조종해' },
        { en: 'coding', ko: '코딩', img: '🧑‍💻', alt: ['code', 'coating'], d: '컴퓨터에게 할 일을 알려줘' },
        { en: 'smart', ko: '똑똑한', img: '🤓', alt: ['smarts', 'mart'], d: '아주 똑똑하다는 말이야' },
        { en: 'magic', ko: '마법', img: '🪄', alt: ['magical'], d: '뿅! 신기한 마법이야' },
        { en: 'shiny', ko: '반짝반짝한', img: '✨', alt: ['shine', 'tiny'], d: '반짝반짝 빛나' },
        { en: 'factory', ko: '공장', img: '🏭', alt: ['factories'], d: '로봇이 일하는 공장이야' },
      ],
      questions: [
        { q: 'What can the robot do?', ko: '로봇은 뭘 할 수 있어?', img: '🤖', answer: 'It can walk.', keywords: ['walk', 'run', 'jump', 'dance', 'talk', 'fly', 'swim', 'work', 'sing'] },
        { q: 'Is it a robot?', ko: '이건 로봇이야?', img: '🤖', answer: 'Yes, it is.', keywords: ['yes', 'yeah', 'it is'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🚀', answer: "It's a rocket.", keywords: ['rocket', 'rockets', 'pocket'] },
        { q: 'Which way?', ko: '어느 쪽이야?', img: '⬆️', answer: 'Up!', keywords: ['up', 'app', 'op'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '💻', answer: "It's a computer.", keywords: ['computer', 'computers', 'laptop'] },
        { q: 'Can the robot talk?', ko: '로봇은 말할 수 있어?', img: '🤖', answer: 'Yes, it can.', keywords: ['yes', 'yeah', 'it can', 'can'] },
        { q: 'Which way?', ko: '어느 쪽이야?', img: '⬇️', answer: 'Down!', keywords: ['down', 'town', 'done'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🔋', answer: "It's a battery.", keywords: ['battery', 'batteries'] },
        { q: 'Can the robot eat?', ko: '로봇은 밥을 먹을 수 있어?', img: '🤖🍎', answer: "No, it can't.", keywords: ['no', "can't", 'cannot', 'can not', 'nope'] },
        { q: 'Where is the rocket going?', ko: '로켓은 어디로 가?', img: '🚀🌕', answer: 'To the moon.', keywords: ['moon', 'space', 'mars', 'sky', 'stars'] },
        { q: 'Which way?', ko: '어느 쪽이야?', img: '⬅️', answer: 'Left!', keywords: ['left', 'lift', 'laughed'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '👽', answer: "It's an alien.", keywords: ['alien', 'aliens'] },
        { q: 'Tell the robot what to do!', ko: '로봇한테 명령해봐!', img: '🤖', answer: 'Robot, jump!', keywords: ['jump', 'walk', 'run', 'stop', 'dance', 'turn', 'go', 'sing', 'sit', 'fly', 'come'] },
        { q: 'Which way?', ko: '어느 쪽이야?', img: '➡️', answer: 'Right!', keywords: ['right', 'write', 'ride', 'white'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🌍', answer: "It's the Earth.", keywords: ['earth', 'world', 'planet'] },
        { q: 'How many buttons are there?', ko: '버튼이 몇 개야?', img: '🔘🔘🔘', answer: 'Three.', keywords: ['three', '3', 'tree', 'free'] },
        { q: 'What color is the robot?', ko: '로봇은 무슨 색이야?', img: '🤖', answer: "It's silver.", keywords: ['silver', 'gray', 'grey', 'white', 'blue'] },
        { q: 'Do you want a robot?', ko: '로봇 갖고 싶어?', img: '🤖', answer: 'Yes, I do!', keywords: ['yes', 'yeah', 'i do', 'no'] },
        { q: 'What can you build?', ko: '뭘 만들 수 있어?', img: '🧱', answer: 'I can build a robot.', keywords: ['robot', 'house', 'car', 'rocket', 'castle', 'tower', 'ship', 'train', 'airplane', 'plane'] },
        { q: 'Can robots fly?', ko: '로봇은 날 수 있어?', img: '🤖', answer: 'Yes, they can!', keywords: ['yes', 'no', 'can', 'yeah', "can't"] },
      ],
    },
    {
      id: 'travel', title: '여행', en: 'Travel', icon: '✈️', sticker: '🗺️', fav: true,
      words: [
        { en: 'car', ko: '자동차', img: '🚗', d: '부릉부릉 달려' },
        { en: 'bus', ko: '버스', img: '🚌', d: '여러 사람이 함께 타' },
        { en: 'train', ko: '기차', img: '🚆', d: '칙칙폭폭 기찻길을 달려' },
        { en: 'airplane', ko: '비행기', img: '✈️', alt: ['plane', 'air plane'], d: '하늘 높이 날아가' },
        { en: 'ship', ko: '배', img: '🚢', d: '바다를 건너가' },
        { en: 'bike', ko: '자전거', img: '🚲', d: '바퀴가 두 개야' },
        { en: 'beach', ko: '해변', img: '🏖️', d: '모래와 파도가 있어' },
        { en: 'mountain', ko: '산', img: '⛰️', d: '높이높이 솟아 있어' },
        { en: 'map', ko: '지도', img: '🗺️', d: '길을 찾을 때 봐' },
        { en: 'bag', ko: '가방', img: '🎒', alt: ['back', 'bug'], d: '물건을 넣어서 메고 다녀' },
        { en: 'taxi', ko: '택시', img: '🚕', alt: ['taxis', 'texas'], d: '노란 택시야' },
        { en: 'truck', ko: '트럭', img: '🚚', alt: ['trucks', 'track'], d: '짐을 싣고 달려' },
        { en: 'helicopter', ko: '헬리콥터', img: '🚁', alt: ['helicopters'], d: '프로펠러가 빙빙 돌아' },
        { en: 'subway', ko: '지하철', img: '🚇', alt: ['sub way'], d: '땅속으로 달리는 기차야' },
        { en: 'fire truck', ko: '소방차', img: '🚒', alt: ['fire engine', 'firetruck'], d: '불을 끄러 달려가' },
        { en: 'police car', ko: '경찰차', img: '🚓', alt: ['police'], d: '삐뽀삐뽀 경찰차야' },
        { en: 'ambulance', ko: '구급차', img: '🚑', alt: ['ambulances'], d: '아픈 사람을 태워 가' },
        { en: 'motorcycle', ko: '오토바이', img: '🏍️', alt: ['motorbike'], d: '부릉부릉 바퀴 두 개야' },
        { en: 'scooter', ko: '킥보드', img: '🛴', alt: ['scooters'], d: '발로 밀면서 타' },
        { en: 'road', ko: '길', img: '🛣️', alt: ['roads', 'rode'], d: '차가 다니는 길이야' },
        { en: 'bridge', ko: '다리', img: '🌉', alt: ['bridges'], d: '강을 건너는 다리야' },
        { en: 'ticket', ko: '표', img: '🎫', alt: ['tickets'], d: '기차나 버스를 탈 때 필요해' },
        { en: 'passport', ko: '여권', img: '🛂', alt: ['passports'], d: '외국에 갈 때 필요해' },
        { en: 'suitcase', ko: '여행 가방', img: '🧳', alt: ['suit case'], d: '바퀴 달린 여행 가방이야' },
        { en: 'hotel', ko: '호텔', img: '🏨', alt: ['hotels'], d: '여행 가서 자는 곳이야' },
        { en: 'tent', ko: '텐트', img: '⛺', alt: ['tents', 'ten'], d: '캠핑할 때 치는 집이야' },
        { en: 'park', ko: '공원', img: '🏞️', alt: ['parks', 'bark'], d: '나무와 풀이 있는 공원이야' },
        { en: 'zoo', ko: '동물원', img: '🦓🦁', alt: ['zoos', 'sue'], d: '동물들을 보러 가는 곳이야' },
        { en: 'aquarium', ko: '수족관', img: '🐠🐙', alt: ['aquariums'], d: '물고기를 보러 가는 곳이야' },
        { en: 'museum', ko: '박물관', img: '🏛️', alt: ['museums'], d: '옛날 물건을 보는 곳이야' },
        { en: 'city', ko: '도시', img: '🏙️', alt: ['cities', 'kitty'], d: '높은 건물이 많은 곳이야' },
        { en: 'farm', ko: '농장', img: '🚜', alt: ['farms', 'firm'], d: '동물과 채소를 키우는 곳이야' },
        { en: 'Korea', ko: '한국', img: '🇰🇷', alt: ['korea', 'south korea', 'career'], d: '우리나라 한국이야' },
        { en: 'world', ko: '세계', img: '🌏', alt: ['word', 'whirled'], d: '여러 나라가 있는 세계야' },
        { en: 'compass', ko: '나침반', img: '🧭', alt: ['compasses'], d: '방향을 알려줘' },
        { en: 'sunglasses', ko: '선글라스', img: '🕶️', alt: ['sun glasses'], d: '햇빛을 막아주는 안경이야' },
        { en: 'tower', ko: '탑', img: '🗼', alt: ['towers', 'tour'], d: '높이 솟은 탑이야' },
        { en: 'ferris wheel', ko: '대관람차', img: '🎡', alt: ['ferris', 'wheel'], d: '빙글빙글 높이 올라가' },
        { en: 'roller coaster', ko: '롤러코스터', img: '🎢', alt: ['coaster', 'rollercoaster'], d: '슝 빠르게 내려가' },
        { en: 'traffic light', ko: '신호등', img: '🚦', alt: ['traffic lights', 'traffic'], d: '빨간불엔 멈추고 초록불엔 건너' },
        { en: 'gas station', ko: '주유소', img: '⛽', alt: ['gas'], d: '차에 기름을 넣는 곳이야' },
        { en: 'station', ko: '역', img: '🚉', alt: ['stations'], d: '기차를 타는 곳이야' },
        { en: 'snowman', ko: '눈사람', img: '☃️', alt: ['snow man'], d: '눈으로 만든 사람이야' },
        { en: 'sled', ko: '썰매', img: '🛷', alt: ['sleds', 'slide'], d: '눈 위에서 슝 타' },
        { en: 'ski', ko: '스키', img: '⛷️', alt: ['skiing', 'sky'], d: '눈 위를 미끄러져 내려와' },
        { en: 'drive', ko: '운전하다', img: '🚙', alt: ['driving', 'dry'], d: '차를 운전하는 거야' },
        { en: 'ride', ko: '타다', img: '🎠', alt: ['right', 'riding'], d: '회전목마를 타' },
        { en: 'pilot', ko: '조종사', img: '🧑‍✈️', alt: ['pilots'], d: '비행기를 조종하는 사람이야' },
        { en: 'picnic', ko: '소풍', img: '🧺', alt: ['picnics'], d: '도시락 싸서 놀러 가' },
        { en: 'vacation', ko: '방학·휴가', img: '🏝️', alt: ['vacations'], d: '쉬면서 놀러 가는 때야' },
      ],
      questions: [
        { q: 'Where do you want to go?', ko: '어디 가고 싶어?', answer: 'I want to go to the beach.', keywords: ['beach', 'mountain', 'zoo', 'park', 'sea', 'jeju', 'aquarium', 'museum', 'school', 'home'] },
        { q: 'How do you get there?', ko: '뭐 타고 가?', img: '✈️', answer: 'By airplane.', keywords: ['airplane', 'plane', 'air plane'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🚌', answer: "It's a bus.", keywords: ['bus', 'buses'] },
        { q: 'Where is the airplane?', ko: '비행기는 어디 있어?', img: '✈️☁️', answer: 'In the sky.', keywords: ['sky', 'skies', 'air', 'cloud'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🚆', answer: "It's a train.", keywords: ['train', 'trains'] },
        { q: 'Do you like trains?', ko: '기차 좋아해?', img: '🚆', answer: 'Yes, I do.', keywords: ['yes', 'no', 'yeah', 'i do'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🚗', answer: "It's a car.", keywords: ['car', 'cars'] },
        { q: 'Can a car fly?', ko: '자동차는 날 수 있어?', img: '🚗', answer: "No, it can't.", keywords: ['no', "can't", 'cannot', 'can not', 'nope'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🚢', answer: "It's a ship.", keywords: ['ship', 'ships', 'sheep'] },
        { q: 'What color is the fire truck?', ko: '소방차는 무슨 색이야?', img: '🚒', answer: "It's red.", keywords: ['red', 'read'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🚲', answer: "It's a bike.", keywords: ['bike', 'bicycle', 'bikes'] },
        { q: 'How do you go to school?', ko: '학교에 어떻게 가?', img: '🏫', answer: 'I walk to school.', keywords: ['walk', 'bus', 'car', 'bike', 'foot', 'subway', 'train'] },
        { q: 'Is the airplane fast or slow?', ko: '비행기는 빨라, 느려?', img: '✈️', answer: "It's fast.", keywords: ['fast', 'first'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🚁', answer: "It's a helicopter.", keywords: ['helicopter', 'helicopters'] },
        { q: 'What color is the taxi?', ko: '택시는 무슨 색이야?', img: '🚕', answer: "It's yellow.", keywords: ['yellow', 'orange'] },
        { q: "Let's go!", ko: '가자!', answer: "Let's go!", keywords: ["let's go", 'lets go', 'go', 'okay', 'ok'] },
        { q: 'Where is the ship?', ko: '배는 어디 있어?', img: '🚢🌊', answer: 'On the sea.', keywords: ['sea', 'see', 'water', 'ocean'] },
        { q: 'What do you pack in your bag?', ko: '가방에 뭘 넣어?', img: '🎒', answer: 'My toys.', keywords: ['toy', 'toys', 'clothes', 'book', 'books', 'snack', 'snacks', 'water', 'camera', 'hat', 'robot'] },
        { q: 'Is the mountain high?', ko: '산이 높아?', img: '⛰️', answer: "Yes, it's high.", keywords: ['yes', 'high', 'tall', 'big', 'yeah'] },
        { q: 'Where are you going?', ko: '어디 가?', img: '🗺️', answer: "I'm going to the zoo.", keywords: ['zoo', 'park', 'beach', 'sea', 'mountain', 'school', 'home', 'museum', 'aquarium', 'jeju', 'store', 'library', 'hospital'] },
      ],
    },
    {
      id: 'science', title: '과학실험', en: 'Science Lab', icon: '🔬', sticker: '🧪', fav: true,
      mission: '집에서 해봐요! 컵에 물을 담고 얼음을 넣어요. "Put the ice in the water. Is it cold?" 현이랑 같이 손으로 만져보고 영어로 말해봐요.',
      words: [
        { en: 'ice', ko: '얼음', img: '🧊', alt: ['eyes', 'nice'], d: '꽁꽁 차가워' },
        { en: 'hot', ko: '뜨거운', img: '🔥', alt: ['hat', 'hut'], d: '앗 뜨거워' },
        { en: 'cold', ko: '차가운', img: '❄️', alt: ['called', 'code'], d: '으슬으슬 차가워' },
        { en: 'magnet', ko: '자석', img: '🧲', d: '쇠붙이를 착 붙여' },
        { en: 'mix', ko: '섞다', img: '🥣', alt: ['max', 'mics'], d: '휘휘 섞는 거야' },
        { en: 'microscope', ko: '현미경', img: '🔬', d: '작은 걸 크게 보여줘' },
        { en: 'test tube', ko: '시험관', img: '🧪', alt: ['tube', 'test'], d: '실험할 때 쓰는 작은 유리관이야' },
        { en: 'rainbow', ko: '무지개', img: '🌈', d: '일곱 색깔이 있어' },
        { en: 'sun', ko: '해', img: '☀️', alt: ['son', 'some'], d: '밝고 따뜻하게 빛나' },
        { en: 'balloon', ko: '풍선', img: '🎈', d: '둥실둥실 떠올라' },
        { en: 'rain', ko: '비', img: '🌧️', alt: ['rainy', 'train', 'raining'], d: '하늘에서 톡톡 떨어지는 비야' },
        { en: 'cloud', ko: '구름', img: '☁️', alt: ['clouds'], d: '하늘에 둥실 떠 있어' },
        { en: 'wind', ko: '바람', img: '🌬️', alt: ['windy', 'win'], d: '휘잉 부는 바람이야' },
        { en: 'snow', ko: '눈', img: '🌨️', alt: ['snowy', 'slow', 'no'], d: '하얗게 펑펑 내려' },
        { en: 'shadow', ko: '그림자', img: '👤', alt: ['shadows'], d: '빛을 가리면 생겨' },
        { en: 'mirror', ko: '거울', img: '🪞', alt: ['mirrors'], d: '내 얼굴이 보여' },
        { en: 'melt', ko: '녹다', img: '🧊💧', alt: ['melts', 'milk', 'melting'], d: '얼음이 녹아서 물이 돼' },
        { en: 'freeze', ko: '얼다', img: '💧🧊', alt: ['freezes', 'frees', 'please'], d: '물이 꽁꽁 얼어' },
        { en: 'steam', ko: '김', img: '♨️', alt: ['team', 'stim'], d: '뜨거운 물에서 올라와' },
        { en: 'smoke', ko: '연기', img: '💨', alt: ['smokes', 'smog'], d: '뿌옇게 올라가' },
        { en: 'lightning', ko: '번개', img: '🌩️', alt: ['lighting'], d: '번쩍 하늘이 빛나' },
        { en: 'weather', ko: '날씨', img: '🌦️', alt: ['whether', 'feather'], d: '맑음, 비, 눈, 날씨야' },
        { en: 'thermometer', ko: '온도계', img: '🌡️', alt: ['thermometers'], d: '얼마나 더운지 재' },
        { en: 'heavy', ko: '무거운', img: '🏋️', alt: ['heavily', 'happy'], d: '낑낑 무겁다는 말이야' },
        { en: 'drop', ko: '물방울', img: '💧', alt: ['drops', 'drip'], d: '똑 떨어지는 물방울이야' },
        { en: 'measure', ko: '재다', img: '📐', alt: ['measures', 'major'], d: '길이를 재는 거야' },
        { en: 'scientist', ko: '과학자', img: '🧑‍🔬', alt: ['scientists'], d: '실험하는 과학자야' },
        { en: 'lab coat', ko: '실험복', img: '🥼', alt: ['lab', 'coat'], d: '실험할 때 입는 하얀 옷이야' },
        { en: 'gloves', ko: '장갑', img: '🧤', alt: ['glove', 'loves'], d: '손을 지켜줘' },
        { en: 'DNA', ko: '유전자', img: '🧬', alt: ['dna', 'd n a'], d: '몸의 설계도야' },
        { en: 'germ', ko: '세균', img: '🦠', alt: ['germs', 'jam'], d: '눈에 안 보이는 아주 작은 균이야' },
        { en: 'volcano', ko: '화산', img: '🌋', alt: ['volcanoes'], d: '뜨거운 용암이 펑 터져' },
        { en: 'telescope', ko: '망원경', img: '🔭', alt: ['telescopes'], d: '멀리 있는 별을 봐' },
        { en: 'pull', ko: '당기다', img: '🪢', alt: ['pool', 'full'], d: '줄을 당기는 거야' },
        { en: 'spin', ko: '빙글빙글', img: '🌀', alt: ['spinning', 'spoon'], d: '빙글빙글 도는 거야' },
        { en: 'sound', ko: '소리', img: '🔔', alt: ['sounds', 'found'], d: '귀로 듣는 소리야' },
        { en: 'loud', ko: '시끄러운', img: '📢', alt: ['allowed'], d: '소리가 아주 커' },
        { en: 'quiet', ko: '조용한', img: '🔇', alt: ['quite', 'quiet please'], d: '쉿, 아주 조용해' },
        { en: 'soft', ko: '부드러운', img: '🪶', alt: ['soft ly'], d: '깃털처럼 보들보들해' },
        { en: 'pop', ko: '펑', img: '💥', alt: ['pup', 'pops'], d: '풍선이 펑 터져' },
        { en: 'soap', ko: '비누', img: '🧼', alt: ['soup', 'soaps'], d: '거품이 뽀글뽀글 나' },
        { en: 'sponge', ko: '스펀지', img: '🧽', alt: ['sponges'], d: '물을 쭉 빨아들여' },
        { en: 'paper', ko: '종이', img: '📄', alt: ['papers', 'pepper'], d: '얇은 종이야' },
        { en: 'wood', ko: '나무 조각', img: '🪵', alt: ['would', 'woods'], d: '나무로 된 거야' },
        { en: 'fossil', ko: '화석', img: '🦕', alt: ['fossils'], d: '아주 옛날 공룡 흔적이야' },
        { en: 'crystal', ko: '수정', img: '🔮', alt: ['crystals'], d: '반짝이는 돌이야' },
        { en: 'grow', ko: '자라다', img: '🌱🌳', alt: ['grows', 'glow'], d: '쑥쑥 자라는 거야' },
        { en: 'zoom', ko: '확대하다', img: '🔍', alt: ['zooms', 'room'], d: '크게 확대해서 봐' },
        { en: 'tornado', ko: '회오리바람', img: '🌪️', alt: ['tornadoes'], d: '빙글빙글 도는 센 바람이야' },
        { en: 'fog', ko: '안개', img: '🌫️', alt: ['frog', 'fox'], d: '뿌옇게 앞이 안 보여' },
      ],
      questions: [
        { q: 'Is it hot or cold?', ko: '이건 뜨거워, 차가워?', img: '🧊', answer: "It's cold.", keywords: ['cold', 'called', 'code', 'cool'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🧲', answer: "It's a magnet.", keywords: ['magnet', 'magnets'] },
        { q: 'Is it hot or cold?', ko: '이건 뜨거워, 차가워?', img: '🔥', answer: "It's hot.", keywords: ['hot', 'hat', 'hut'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🌈', answer: "It's a rainbow.", keywords: ['rainbow', 'rainbows'] },
        { q: "What's the weather like?", ko: '날씨가 어때?', img: '☀️', answer: "It's sunny.", keywords: ['sunny', 'sun', 'hot', 'sonny'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🎈', answer: "It's a balloon.", keywords: ['balloon', 'balloons'] },
        { q: "What's the weather like?", ko: '날씨가 어때?', img: '🌧️', answer: "It's rainy.", keywords: ['rain', 'rainy', 'raining'] },
        { q: 'What does ice become?', ko: '얼음이 녹으면 뭐가 돼?', img: '🧊☀️', answer: 'Water.', keywords: ['water', 'waters'] },
        { q: "What's this?", ko: '이건 뭐야?', img: '🔬', answer: "It's a microscope.", keywords: ['microscope', 'microscopes'] },
        { q: "What's the weather like?", ko: '날씨가 어때?', img: '🌨️', answer: "It's snowy.", keywords: ['snow', 'snowy', 'snowing'] },
        { q: 'Can a magnet pick up a spoon?', ko: '자석은 숟가락을 붙일 수 있어?', img: '🧲🥄', answer: 'Yes, it can.', keywords: ['yes', 'yeah', 'it can', 'can'] },
        { q: 'Mix red and yellow. What color?', ko: '빨강이랑 노랑을 섞으면 무슨 색?', img: '🔴🟡', answer: 'Orange!', keywords: ['orange'] },
        { q: 'Is it windy?', ko: '바람이 불어?', img: '🌬️', answer: "Yes, it's windy.", keywords: ['yes', 'windy', 'yeah', 'wind'] },
        { q: 'Can a magnet pick up paper?', ko: '자석은 종이를 붙일 수 있어?', img: '🧲📄', answer: "No, it can't.", keywords: ['no', "can't", 'cannot', 'can not', 'nope'] },
        { q: 'Mix blue and yellow. What color?', ko: '파랑이랑 노랑을 섞으면 무슨 색?', img: '🔵🟡', answer: 'Green!', keywords: ['green', 'grin'] },
        { q: 'How many colors are in a rainbow?', ko: '무지개는 몇 가지 색이야?', img: '🌈', answer: 'Seven.', keywords: ['seven', '7', 'heaven'] },
        { q: 'Is a feather heavy or light?', ko: '깃털은 무거워, 가벼워?', img: '🪶', answer: "It's light.", keywords: ['light', 'lite', 'right'] },
        { q: "What's in the sky at night?", ko: '밤하늘에는 뭐가 있어?', img: '🌃', answer: 'The moon and stars.', keywords: ['moon', 'star', 'stars'] },
        { q: 'Is the rock heavy or light?', ko: '돌은 무거워, 가벼워?', img: '🪨', answer: "It's heavy.", keywords: ['heavy', 'happy'] },
        { q: 'Do you like experiments?', ko: '실험 좋아해?', img: '🧪', answer: 'Yes, I do!', keywords: ['yes', 'yeah', 'i do', 'no'] },
      ],
    },
    {
      id: 'actions', title: '할 수 있어요', en: 'Actions', icon: '🏃', sticker: '🏆',
      words: [
        { en: 'run', ko: '달리다', img: '🏃', alt: ['ran', 'fun'], d: '빨리빨리 달리는 거야' },
        { en: 'jump', ko: '뛰다', img: '🦘', d: '폴짝 뛰어오르는 거야' },
        { en: 'swim', ko: '수영하다', img: '🏊', d: '물에서 헤엄치는 거야' },
        { en: 'fly', ko: '날다', img: '🕊️', alt: ['fry', 'flight'], d: '하늘을 나는 거야' },
        { en: 'dance', ko: '춤추다', img: '💃', d: '신나게 춤추는 거야' },
        { en: 'sing', ko: '노래하다', img: '🎤', alt: ['sink', 'thing'], d: '노래를 부르는 거야' },
        { en: 'eat', ko: '먹다', img: '🍽️', alt: ['it'], d: '냠냠 먹는 거야' },
        { en: 'read', ko: '읽다', img: '📖', alt: ['red'], d: '책을 읽는 거야' },
        { en: 'draw', ko: '그리다', img: '🖍️', d: '그림을 그리는 거야' },
        { en: 'climb', ko: '오르다', img: '🧗', d: '높이 올라가는 거야' },
        { en: 'sit', ko: '앉다', img: '🪑', alt: ['set', 'seat', 'sit down'], d: '의자에 앉는 거야' },
        { en: 'stand', ko: '서다', img: '🧍', alt: ['stand up', 'stands'], d: '똑바로 서는 거야' },
        { en: 'sleep', ko: '자다', img: '🛌', alt: ['sleeping', 'slip'], d: '쿨쿨 자는 거야' },
        { en: 'drink', ko: '마시다', img: '🧃', alt: ['drinks', 'drank'], d: '꿀꺽꿀꺽 마시는 거야' },
        { en: 'write', ko: '쓰다', img: '✍️', alt: ['right', 'writing'], d: '글씨를 쓰는 거야' },
        { en: 'cook', ko: '요리하다', img: '🧑‍🍳', alt: ['cooking', 'cake'], d: '맛있는 요리를 해' },
        { en: 'kick', ko: '차다', img: '⚽', alt: ['kicks', 'kid'], d: '공을 뻥 차는 거야' },
        { en: 'throw', ko: '던지다', img: '🤾', alt: ['through', 'throws'], d: '공을 휙 던지는 거야' },
        { en: 'catch', ko: '받다', img: '🥎', alt: ['cats', 'ketch'], d: '공을 탁 잡는 거야' },
        { en: 'ride', ko: '타다', img: '🚴', alt: ['right', 'riding'], d: '자전거를 타는 거야' },
        { en: 'wash', ko: '씻다', img: '🚿', alt: ['washing'], d: '깨끗이 씻는 거야' },
        { en: 'brush', ko: '닦다', img: '🪥', alt: ['brushing', 'rush'], d: '이를 치카치카 닦아' },
        { en: 'open', ko: '열다', img: '🔓', alt: ['opens', 'opening'], d: '문을 여는 거야' },
        { en: 'close', ko: '닫다', img: '🔒', alt: ['clothes', 'closed'], d: '문을 닫는 거야' },
        { en: 'listen', ko: '듣다', img: '🎧', alt: ['listening', 'lesson'], d: '귀 기울여 듣는 거야' },
        { en: 'watch', ko: '보다', img: '🎬', alt: ['watching'], d: '영화나 만화를 봐' },
        { en: 'cut', ko: '자르다', img: '✂️', alt: ['cat', 'cute'], d: '가위로 싹둑 잘라' },
        { en: 'skate', ko: '스케이트 타다', img: '⛸️', alt: ['skating', 'skates'], d: '얼음 위를 쌩쌩 달려' },
        { en: 'hop', ko: '깡충 뛰다', img: '🐇', alt: ['hope', 'hot'], d: '한 발로 깡충깡충 뛰어' },
        { en: 'flip', ko: '재주넘기', img: '🤸', alt: ['flips', 'flipping'], d: '데굴 재주를 넘어' },
        { en: 'roll', ko: '굴리다', img: '🎳', alt: ['role', 'rolls'], d: '공을 데굴데굴 굴려' },
        { en: 'hit', ko: '치다', img: '⚾', alt: ['heat', 'hits'], d: '방망이로 공을 딱 쳐' },
        { en: 'shout', ko: '외치다', img: '📣', alt: ['shoot', 'shouts'], d: '크게 소리 지르는 거야' },
        { en: 'seek', ko: '찾다', img: '🔎', alt: ['sick', 'seeking'], d: '숨은 걸 찾는 거야' },
        { en: 'wait', ko: '기다리다', img: '⏳', alt: ['weight', 'waiting'], d: '차례를 기다려' },
        { en: 'go', ko: '가다', img: '🟢', alt: ['goes', 'going'], d: '출발! 가는 거야' },
        { en: 'win', ko: '이기다', img: '🏆', alt: ['won', 'when'], d: '경기에서 이겼어' },
        { en: 'shop', ko: '장보다', img: '🛒', alt: ['shopping', 'chop'], d: '물건을 사러 가' },
        { en: 'study', ko: '공부하다', img: '📝', alt: ['studying'], d: '열심히 공부해' },
        { en: 'spell', ko: '철자를 말하다', img: '🔤', alt: ['spelling', 'smell'], d: '글자를 하나씩 말해' },
        { en: 'dream', ko: '꿈꾸다', img: '💭', alt: ['dreams', 'dreaming'], d: '잠자면서 꿈을 꿔' },
        { en: 'wake up', ko: '일어나다', img: '⏰', alt: ['wake', 'awake'], d: '아침에 일어나' },
        { en: 'bow', ko: '인사하다', img: '🙇', alt: ['bowl', 'bows'], d: '허리 숙여 인사해' },
        { en: 'lift', ko: '들어 올리다', img: '🏋️', alt: ['left', 'lifts'], d: '무거운 걸 번쩍 들어' },
        { en: 'wear', ko: '입다', img: '👗', alt: ['where', 'wearing'], d: '옷을 입는 거야' },
        { en: 'row', ko: '노를 젓다', img: '🚣', alt: ['road', 'rowing'], d: '배의 노를 저어' },
        { en: 'knock', ko: '노크하다', img: '🚪', alt: ['knocks', 'not'], d: '똑똑 문을 두드려' },
        { en: 'play', ko: '놀다', img: '🎲', alt: ['plays', 'playing'], d: '신나게 노는 거야' },
        { en: 'sweep', ko: '쓸다', img: '🧹', alt: ['sweeping', 'swipe'], d: '빗자루로 쓱쓱 쓸어' },
        { en: 'tickle', ko: '간지럽히다', img: '🤭', alt: ['tickles', 'tickling'], d: '간질간질 간지럽혀' },
      ],
      questions: [
        { q: 'Can you swim?', ko: '수영할 수 있어?', img: '🏊', answer: 'Yes, I can.', keywords: ['yes', 'no', 'yeah', 'i can', 'can'] },
        { q: 'What do you like to do?', ko: '뭐 하는 거 좋아해?', answer: 'I like to draw.', keywords: ['run', 'jump', 'swim', 'dance', 'sing', 'read', 'draw', 'play', 'climb', 'eat', 'fly'] },
        { q: 'What is he doing?', ko: '이 아이는 뭐 하고 있어?', img: '🏃', answer: "He's running.", keywords: ['run', 'running', 'ran'] },
        { q: 'Can you jump?', ko: '뛸 수 있어?', img: '🦘', answer: 'Yes, I can!', keywords: ['yes', 'yeah', 'i can', 'can'] },
        { q: 'What is she doing?', ko: '이 아이는 뭐 하고 있어?', img: '💃', answer: "She's dancing.", keywords: ['dance', 'dancing'] },
        { q: 'Can you fly?', ko: '날 수 있어?', img: '🕊️', answer: "No, I can't!", keywords: ['no', "can't", 'cannot', 'can not', 'nope'] },
        { q: 'What is he doing?', ko: '이 아이는 뭐 하고 있어?', img: '🏊', answer: "He's swimming.", keywords: ['swim', 'swimming'] },
        { q: "Let's dance!", ko: '같이 춤추자!', img: '💃', answer: "Okay! Let's dance!", keywords: ['okay', 'ok', 'dance', "let's", 'yes', 'sure'] },
        { q: 'What is she doing?', ko: '이 아이는 뭐 하고 있어?', img: '🎤', answer: "She's singing.", keywords: ['sing', 'singing'] },
        { q: 'Can you ride a bike?', ko: '자전거 탈 수 있어?', img: '🚴', answer: 'Yes, I can.', keywords: ['yes', 'no', 'yeah', 'i can', 'can'] },
        { q: 'What is he doing?', ko: '이 아이는 뭐 하고 있어?', img: '🧑‍🍳', answer: "He's cooking.", keywords: ['cook', 'cooking'] },
        { q: 'Jump three times!', ko: '세 번 뛰어!', img: '🦘', answer: 'One, two, three!', keywords: ['three', '3', 'one', 'two', 'tree'] },
        { q: 'What is she doing?', ko: '이 아이는 뭐 하고 있어?', img: '🧗', answer: "She's climbing.", keywords: ['climb', 'climbing'] },
        { q: 'Do you like to sing?', ko: '노래하는 거 좋아해?', img: '🎤', answer: 'Yes, I do.', keywords: ['yes', 'no', 'yeah', 'i do'] },
        { q: 'What is he doing?', ko: '이 아이는 뭐 하고 있어?', img: '🛌', answer: "He's sleeping.", keywords: ['sleep', 'sleeping'] },
        { q: 'Stand up!', ko: '일어나!', img: '🧍', answer: 'Okay!', keywords: ['okay', 'ok', 'stand', 'yes', 'sure'] },
        { q: 'What is she doing?', ko: '이 아이는 뭐 하고 있어?', img: '✍️', answer: "She's writing.", keywords: ['write', 'writing', 'riding'] },
        { q: 'Can you kick a ball?', ko: '공을 찰 수 있어?', img: '⚽', answer: 'Yes, I can.', keywords: ['yes', 'no', 'yeah', 'i can', 'can'] },
        { q: 'What do you do after school?', ko: '학교 끝나면 뭐 해?', img: '🏫', answer: 'I play with my friends.', keywords: ['play', 'read', 'draw', 'sing', 'swim', 'run', 'study', 'watch', 'taekwondo', 'piano', 'homework', 'sleep', 'eat'] },
        { q: 'Who wins?', ko: '누가 이겼어?', img: '🏆', answer: 'I win!', keywords: ['win', 'i win', 'me', 'won'] },
      ],
    },
  ],

  // 예전 방식의 한국어 설명 (단어의 d 가 없을 때만 써요)
  wordDesc: {},

  // 로봇 친구가 하는 영어 말 (원어민 녹음 파일이 audio 폴더에 있어요. 고치면 녹음 대신 기기 음성으로 나와요)
  lines: {
    hi: 'Hi, {NAME}!',
    greet: 'Hi, {NAME}! How are you today?',
    feelings: {
      happy: ["I'm happy!", "Yay! Me too! Let's get started!"],
      great: ["I'm great!", "Awesome! Let's get started!"],
      sleepy: ["I'm sleepy!", "Let's wake up with some English!"],
      hungry: ["I'm hungry!", "Me too! Let's learn first, then snack time!"],
      sad: ["I'm sad.", "Aww. Let's have some fun together!"],
    },
    greetOk: "Great! Let's get started!",
    praise: ['Great job!', 'Awesome!', 'You got it!', 'Nice work, {NAME}!', 'Perfect!', "Yes! That's right!", 'Well done!', 'Wow, super!'],
  },

  // 함께하는 친구들 (앱 속 캐릭터)
  friends: {
    eunhoo: { name: '은후', color: '#ffb74d', role: '같이 문제 푸는 친구' },
    chorok: { name: '초록', color: '#66bb6a', role: '윤이가 가르쳐주는 동생' },
    hyun: { name: '현', color: '#64b5f6', role: '윤이가 가르쳐주는 동생' },
  },
};
